"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { type Category, type Exercise, type Workout } from "@/lib/training-data";
import { getWorkoutSessions } from "@/lib/session-storage";
import { loadExercises, loadWorkouts } from "@/lib/training-storage";
import {
  WORKOUT_OVERRIDE_PREFIX,
  WEEKLY_WORKOUT_PLAN,
  buildWorkoutStorageKey,
  getDefaultWorkoutProgress,
  getDateForWeekday,
  getTodayDateKey,
  parseWorkoutProgress,
  toLocalDateKey,
} from "@/lib/workout";
import { buildWeeklyPlan, type DayKey, type WeekConfig } from "@/lib/planner";
import {
  buildGeneratedWorkout,
  getFocusProfile,
  pickSubcategoryForDay,
} from "@/lib/player-workout-engine";
import {
  MANUAL_DAY_WORKOUTS_KEY,
  storedRegenerationSignals,
  type PlannedWorkoutTag,
  readManualDayDisabledMap,
  writeManualDayDisabledMap,
  writeWeeklyRegenSlotMap,
} from "@/lib/activity-calendar";
import { weeklyRecoverySuggestionSlotVisible } from "@/lib/weekly-regeneration";
import WeeklyBasketballCoach from "@/components/WeeklyBasketballCoach";
import TopSubTabs from "@/components/TopSubTabs";
import PageHeader from "@/components/PageHeader";
import { buildBasketballCoachingPriorities } from "@/lib/basketball-coaching";
import { getProgressionState } from "@/lib/level-system";
import { loadTrainingGoalsBundle } from "@/lib/training-goals";

const weekdayOrder = [1, 2, 3, 4, 5, 6, 0] as const;
const HIDDEN_AUTO_WORKOUTS_KEY = "bt.hidden-auto-workouts.v1";

const weekdayNames: Record<(typeof weekdayOrder)[number], string> = {
  0: "Sonntag",
  1: "Montag",
  2: "Dienstag",
  3: "Mittwoch",
  4: "Donnerstag",
  5: "Freitag",
  6: "Samstag",
};
const REST_QUOTES = [
  "Champions train, but they also recover smart. — LeBron James",
  "Rest at the end, not in the middle. — Kobe Bryant",
  "Small daily improvements are the key to staggering long-term results. — Ray Allen",
  "Success is where preparation and opportunity meet. — Stephen Curry",
];

const dayByIndex: Record<(typeof weekdayOrder)[number], DayKey> = {
  0: "sunday",
  1: "monday",
  2: "tuesday",
  3: "wednesday",
  4: "thursday",
  5: "friday",
  6: "saturday",
};
type ManualDayWorkout = {
  id: string;
  title: string;
  sport: "Basketball" | "Gym" | "Home" | "Regeneration" | "Rest";
  subcategory: string;
  notes: string;
  exerciseIds: string[];
  /** Bei „Auf morgen verschieben“ wird die Original-Dauer übernommen, sodass die Karte die richtige Länge zeigt. */
  durationMin?: number;
};

type ProfileLocalCache = {
  profile: {
    favorite_position: string | null;
  };
  playStyle: string;
  weekConfig: WeekConfig;
  weeklyGoalSessions: number;
};

type PlannedUiEntry = {
  day: DayKey;
  sessionType: string;
  intensity: string;
  minutes: number;
  reason: string;
};

type SuggestedWorkout = {
  workoutId?: string;
  title: string;
  durationMin: number;
  notes: string;
  sport: string;
  subcategory: string;
  exerciseIds?: string[];
  exercises?: string[];
  isAutoGenerated?: boolean;
};

type WorkoutCardItem = {
  id: string;
  title: string;
  sport: string;
  subcategory: string;
  notes: string;
  workoutId?: string;
  autoSuggestion?: SuggestedWorkout;
  manualWorkoutId?: string;
  durationMin: number;
};

type HiddenAutoWorkoutsMap = Record<string, string[]>;

function buildAutoWorkoutId(dayIndex: (typeof weekdayOrder)[number], sport: string) {
  if (sport === "Regeneration") return `auto-weekly-recovery-${dayIndex}`;
  return `auto-weekly-${dayIndex}`;
}

function createManualEntryId(): string {
  const random =
    typeof globalThis !== "undefined" && typeof globalThis.crypto?.randomUUID === "function"
      ? globalThis.crypto.randomUUID()
      : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
  return `manual-day-${random}`;
}

function dedupeManualEntries(entries: ManualDayWorkout[]): ManualDayWorkout[] {
  const seen = new Set<string>();
  const out: ManualDayWorkout[] = [];
  for (const entry of entries) {
    if (seen.has(entry.id)) continue;
    seen.add(entry.id);
    out.push(entry);
  }
  return out;
}

function dedupeManualMap(map: Record<string, ManualDayWorkout[]>): Record<string, ManualDayWorkout[]> {
  const out: Record<string, ManualDayWorkout[]> = {};
  let changed = false;
  for (const [key, entries] of Object.entries(map)) {
    const cleaned = dedupeManualEntries(entries);
    if (cleaned.length !== entries.length) changed = true;
    out[key] = cleaned;
  }
  return changed ? out : map;
}

function readHiddenAutoWorkoutsMap(): HiddenAutoWorkoutsMap {
  const raw = window.localStorage.getItem(HIDDEN_AUTO_WORKOUTS_KEY);
  if (!raw) return {};
  try {
    return JSON.parse(raw) as HiddenAutoWorkoutsMap;
  } catch {
    return {};
  }
}

function writeHiddenAutoWorkoutsMap(value: HiddenAutoWorkoutsMap) {
  window.localStorage.setItem(HIDDEN_AUTO_WORKOUTS_KEY, JSON.stringify(value));
}


function encodeAutoWorkoutSuggestion(suggestion: SuggestedWorkout) {
  const payload = {
    title: suggestion.title,
    sport: suggestion.sport,
    subcategory: suggestion.subcategory,
    notes: suggestion.notes,
    exerciseIds: suggestion.exerciseIds ?? [],
    exercises: suggestion.exercises ?? [],
  };

  try {
    return encodeURIComponent(JSON.stringify(payload));
  } catch {
    return null;
  }
}

function roundUpToNearestFive(value: number) {
  return Math.ceil(value / 5) * 5;
}

function normalizeExerciseFamily(name: string) {
  return name
    .toLowerCase()
    .replace(/\s*-\s*(rechts|links|right|left)\b/g, "")
    .replace(/\s*[-–]?\s*\d+\s*$/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function buildRelatedExerciseNames(
  workout: Workout,
  exercises: Exercise[],
  exercisesById: Record<string, Exercise>,
) {
  const baseExercises = workout.exerciseIds
    .map((exerciseId) => exercisesById[exerciseId])
    .filter((exercise): exercise is Exercise => Boolean(exercise));
  const familyKeys = new Set(baseExercises.map((exercise) => normalizeExerciseFamily(exercise.name)));
  const related = exercises.filter(
    (exercise) =>
      exercise.category === workout.category &&
      exercise.subcategory === workout.subcategory &&
      familyKeys.has(normalizeExerciseFamily(exercise.name)),
  );
  const mergedNames = [...baseExercises.map((exercise) => exercise.name), ...related.map((exercise) => exercise.name)];
  return [...new Set(mergedNames)];
}

function getSeedIndex(seedSource: string, length: number) {
  if (length <= 0) return 0;
  let hash = 0;
  for (let i = 0; i < seedSource.length; i += 1) {
    hash = (hash * 31 + seedSource.charCodeAt(i)) >>> 0;
  }
  return hash % length;
}

function computeWorkoutDuration(workout: Workout, exercisesById: Record<string, Exercise>) {
  const rawDuration = workout.exerciseIds.reduce((sum, exerciseId) => {
    const exercise = exercisesById[exerciseId];
    return sum + (exercise?.durationMin ?? 10);
  }, 0);

  return roundUpToNearestFive(rawDuration * 1.1);
}

function buildFallbackSuggestion(mode: string, minutes: number): SuggestedWorkout | null {
  if (mode === "none" || mode === "recovery" || minutes <= 0) {
    return {
      title: "Freier Tag",
      durationMin: 0,
      notes: "Heute ist ein freier Tag. Versuche trotzdem eine kleine aktive Gewohnheit zu schaffen 💪",
      sport: "-",
      subcategory: "Frei",
    };
  }

  if (mode === "game") {
    return {
      title: "Spieltag",
      durationMin: minutes,
      notes: "Nur Match-Fokus, kein zusätzliches Workout.",
      sport: "Basketball",
      subcategory: "Game",
    };
  }

  return null;
}

function buildRecoverySuggestion(day: DayKey, exercises: Exercise[]): SuggestedWorkout {
  const generated = buildGeneratedWorkout({
    day,
    category: "Regeneration",
    subcategory: "Mobilität & Dehnung",
    targetMinutes: 15,
    exercisePool: exercises,
  });
  return {
    title: generated.name,
    durationMin: generated.durationMin,
    notes: `Kurz-Recovery: ${generated.notes}`,
    sport: generated.category,
    subcategory: generated.subcategory,
    exerciseIds: generated.exerciseIds,
    exercises: generated.exerciseNames,
    isAutoGenerated: true,
  };
}

function syncNoTimeForDate(dateKey: string) {
  const dailyRaw = window.localStorage.getItem("bt.daily-plan.v1");
  const dailyPlan = dailyRaw ? (JSON.parse(dailyRaw) as Record<string, PlannedWorkoutTag[]>) : {};
  dailyPlan[dateKey] = [];
  window.localStorage.setItem("bt.daily-plan.v1", JSON.stringify(dailyPlan));

  const parsedDate = new Date(`${dateKey}T00:00:00`);
  const dayMap: Record<number, DayKey> = {
    0: "sunday",
    1: "monday",
    2: "tuesday",
    3: "wednesday",
    4: "thursday",
    5: "friday",
    6: "saturday",
  };
  const targetDay = dayMap[parsedDate.getDay()];
  const rawProfile = window.localStorage.getItem("profile_cache_v4");
  if (!rawProfile) return;
  try {
    const parsed = JSON.parse(rawProfile) as { weekConfig?: Partial<Record<DayKey, { mode: string; minutes: number }>> };
        parsed.weekConfig = {
      ...(parsed.weekConfig ?? {}),
      [targetDay]: { mode: "unavailable", minutes: 0 },
    };
    window.localStorage.setItem("profile_cache_v4", JSON.stringify(parsed));
  } catch {
    // noop
  }
}

function isTodayOrFutureDate(dateKey: string) {
  const todayKey = toLocalDateKey(new Date());
  return dateKey >= todayKey;
}

function selectBestWorkout(
  mode: string,
  day: DayKey,
  targetMinutes: number,
  workouts: Workout[],
  exercises: Exercise[],
  exercisesById: Record<string, Exercise>,
  freshnessMapByCategory: Record<Category, Record<string, number>>,
  usedWorkoutIds: Set<string>,
  weeklySubcategoryUsage: Record<Category, Record<string, number>>,
  avoidSubcategories: Partial<Record<Category, string[]>>,
  position: string,
  playStyle: string,
  lastAssignedSubcategoryByCategory: Partial<Record<Category, string>>,
  basketballCoachingPriorities: string[] = [],
): SuggestedWorkout {
  const isGameMode = mode === "game_day" || mode === "game_training";
  const targetWithExtra = isGameMode ? (mode === "game_day" ? 60 : 30) : targetMinutes;
  const modeLabel = isGameMode ? (mode === "game_day" ? "Spieltag Warm-Up" : "Spieltraining Warm-Up") : "Direktes Training";
  if (mode === "recovery") {
    return buildRecoverySuggestion(day, exercises);
  }
  const fallback = buildFallbackSuggestion(mode, targetWithExtra);
  if (fallback) return fallback;

  const desiredCategory: Category =
    mode === "gym" ? "Gym" : "Basketball";
  let focusProfile = getFocusProfile({ position, playStyle });
  if (desiredCategory === "Basketball" && basketballCoachingPriorities.length > 0) {
    focusProfile = {
      ...focusProfile,
      basketball: [...new Set([...basketballCoachingPriorities, ...focusProfile.basketball])],
    };
  }

  const categoryFreshness = freshnessMapByCategory[desiredCategory] ?? {};
  const subcategoryRank = (subcategory: string) => categoryFreshness[subcategory] ?? 0;
  const weeklyUsage = weeklySubcategoryUsage[desiredCategory] ?? {};
  const subcategoryWeeklyCount = (subcategory: string) => weeklyUsage[subcategory] ?? 0;

  const filteredByCategory = workouts.filter((workout) => workout.category === desiredCategory);
  const availableSubcategories = [
    ...new Set(
      filteredByCategory.map((workout) => workout.subcategory),
    ),
  ];
  const preferredSubcategory = isGameMode
    ? "Warm-Up"
    : pickSubcategoryForDay({
        category: desiredCategory,
        focusProfile,
        usage: weeklySubcategoryUsage[desiredCategory] ?? {},
        availableSubcategories,
      });
  if (filteredByCategory.length === 0) {
    const generated = buildGeneratedWorkout({
      day,
      category: desiredCategory,
      subcategory: desiredCategory,
      targetMinutes: roundUpToNearestFive(targetWithExtra),
      exercisePool: exercises,
    });
    return {
      title: generated.name,
      durationMin: generated.durationMin,
      notes: generated.notes,
      sport: generated.category,
      subcategory: generated.subcategory,
      exerciseIds: generated.exerciseIds,
      exercises: generated.exerciseNames,
      isAutoGenerated: true,
    };
  }

  const filtered = filteredByCategory
    .map((workout) => ({
      workout,
      duration: computeWorkoutDuration(workout, exercisesById),
    }))
    .sort((left, right) => {
      if (left.workout.subcategory === preferredSubcategory && right.workout.subcategory !== preferredSubcategory) {
        return -1;
      }
      if (right.workout.subcategory === preferredSubcategory && left.workout.subcategory !== preferredSubcategory) {
        return 1;
      }
      return 0;
    });
  const unusedPool = filtered.filter((entry) => !usedWorkoutIds.has(entry.workout.id));
  const avoidForCategory = avoidSubcategories[desiredCategory] ?? [];
  const withoutAvoidedSubcategories = unusedPool.filter(
    (entry) => !avoidForCategory.includes(entry.workout.subcategory),
  );
  const pool =
    withoutAvoidedSubcategories.length > 0
      ? withoutAvoidedSubcategories
      : unusedPool.length > 0
        ? unusedPool
        : [];
  const nonConsecutivePool = pool.filter(
    (entry) => entry.workout.subcategory !== lastAssignedSubcategoryByCategory[desiredCategory],
  );
  const dayPool = nonConsecutivePool.length > 0 ? nonConsecutivePool : pool;

  if (dayPool.length === 0) {
    const generated = buildGeneratedWorkout({
      day,
      category: desiredCategory,
      subcategory: preferredSubcategory,
      targetMinutes: targetWithExtra,
      exercisePool: exercises,
    });
    weeklySubcategoryUsage[desiredCategory] = {
      ...weeklySubcategoryUsage[desiredCategory],
      [generated.subcategory]:
        (weeklySubcategoryUsage[desiredCategory]?.[generated.subcategory] ?? 0) + 1,
    };
    return {
      title: generated.name,
      durationMin: generated.durationMin,
      notes: `${modeLabel}: ${generated.notes} (keine duplizierten Workouts in dieser Woche).`,
      sport: generated.category,
      subcategory: generated.subcategory,
      exerciseIds: generated.exerciseIds,
      exercises: generated.exerciseNames,
      isAutoGenerated: true,
    };
  }

  const compliantPool = dayPool.filter(
    (entry) =>
      (weeklySubcategoryUsage[desiredCategory]?.[entry.workout.subcategory] ?? 0) <
      (desiredCategory === "Gym" ? 2 : 2),
  );
  const effectivePool = compliantPool.length > 0 ? compliantPool : dayPool;

  const sortedPool = [...effectivePool].sort((a, b) => {
    const weeklyDiff = subcategoryWeeklyCount(a.workout.subcategory) - subcategoryWeeklyCount(b.workout.subcategory);
    if (weeklyDiff !== 0) return weeklyDiff;

    const freshnessDiff = subcategoryRank(a.workout.subcategory) - subcategoryRank(b.workout.subcategory);
    if (freshnessDiff !== 0) return freshnessDiff;

    const durationDiff = Math.abs(a.duration - targetWithExtra) - Math.abs(b.duration - targetWithExtra);
    if (durationDiff !== 0) return durationDiff;

    const aSeed = getSeedIndex(`${day}-${a.workout.id}`, 97);
    const bSeed = getSeedIndex(`${day}-${b.workout.id}`, 97);
    return aSeed - bSeed;
  });
  const best = sortedPool[0];

  const shouldGenerateWorkout =
    best.workout.subcategory !== preferredSubcategory &&
    (weeklySubcategoryUsage[desiredCategory]?.[preferredSubcategory] ?? 0) <
      (desiredCategory === "Gym" ? 2 : 2);

  if (shouldGenerateWorkout) {
    const generated = buildGeneratedWorkout({
      day,
      category: desiredCategory,
      subcategory: preferredSubcategory,
      targetMinutes: targetWithExtra,
      exercisePool: exercises,
    });
    weeklySubcategoryUsage[desiredCategory] = {
      ...weeklySubcategoryUsage[desiredCategory],
      [generated.subcategory]:
        (weeklySubcategoryUsage[desiredCategory]?.[generated.subcategory] ?? 0) + 1,
    };
    return {
      title: generated.name,
      durationMin: generated.durationMin,
      notes: `${modeLabel}: ${generated.notes} Fokus via Spielertyp-Mapping.`,
      sport: generated.category,
      subcategory: generated.subcategory,
      exerciseIds: generated.exerciseIds,
      exercises: generated.exerciseNames,
      isAutoGenerated: true,
    };
  }

  usedWorkoutIds.add(best.workout.id);
  weeklySubcategoryUsage[desiredCategory] = {
    ...weeklySubcategoryUsage[desiredCategory],
    [best.workout.subcategory]: subcategoryWeeklyCount(best.workout.subcategory) + 1,
  };

  return {
    workoutId: best.workout.id,
    title: best.workout.name,
    durationMin: best.duration,
    notes: `${modeLabel}: Match zu ${targetWithExtra} Min (${best.workout.category} • ${best.workout.subcategory})`,
    sport: best.workout.category,
    subcategory: best.workout.subcategory,
    exerciseIds: best.workout.exerciseIds,
    exercises: buildRelatedExerciseNames(best.workout, exercises, exercisesById),
  };
}

export default function WeeklyWorkoutPage() {
  const todayIndex = new Date().getDay() as (typeof weekdayOrder)[number];
  const orderedDays = useMemo(
    () => [...weekdayOrder]
      .sort((left, right) => ((left - todayIndex + 7) % 7) - ((right - todayIndex + 7) % 7)),
    [todayIndex],
  );
  const [plannedEntries, setPlannedEntries] = useState<PlannedUiEntry[] | null>(null);
  const [suggestionsByDay, setSuggestionsByDay] = useState<Record<DayKey, SuggestedWorkout> | null>(null);
  /** Auto-Plan unabhängig von manuellen Einträgen (zeigt echtes Engine-Ergebnis). */
  const [autoSuggestionsByDay, setAutoSuggestionsByDay] = useState<Record<DayKey, SuggestedWorkout> | null>(null);
  const [manualWorkoutsByDate, setManualWorkoutsByDate] = useState<Record<string, ManualDayWorkout[]>>({});
  const [selectedWorkoutByDay, setSelectedWorkoutByDay] = useState<Partial<Record<DayKey, string>>>({});
  const [manualVersion, setManualVersion] = useState(0);
  const [disabledManualDays, setDisabledManualDays] = useState<Record<string, boolean>>({});
  const [hiddenAutoWorkoutsByDate, setHiddenAutoWorkoutsByDate] = useState<HiddenAutoWorkoutsMap>({});
  const [profileVersion, setProfileVersion] = useState(0);
  /** Nur nach Mount gesetzt — vermeidet Hydration-Mismatch (localStorage vs. SSR-Default). */
  const [mesocycleLabel, setMesocycleLabel] = useState<string | null>(null);
  const availableExercises = useMemo(() => loadExercises(), []);
  const sessions = getWorkoutSessions();
  const completedDateSet = new Set(sessions.map((session) => toLocalDateKey(new Date(session.dateISO))));
  const completedWorkoutIdsByDate = sessions.reduce<Record<string, Set<string>>>((acc, session) => {
    const key = toLocalDateKey(new Date(session.dateISO));
    const current = acc[key] ?? new Set<string>();
    current.add(session.workoutId);
    acc[key] = current;
    return acc;
  }, {});

  useEffect(() => {
    const timer = window.setTimeout(() => {
      const raw = window.localStorage.getItem("profile_cache_v4");
      if (!raw) return;

      try {
        const parsed = JSON.parse(raw) as ProfileLocalCache;
        const mesocyclePhase = loadTrainingGoalsBundle().mesocyclePhase;
        const computed = buildWeeklyPlan({
          position: parsed.profile.favorite_position ?? "sg",
          playStyle: parsed.playStyle,
          weekConfig: parsed.weekConfig,
          weeklyGoalSessions: parsed.weeklyGoalSessions,
          mesocyclePhase,
        });

        setPlannedEntries(computed);

        const exercises = loadExercises();
        const workouts = loadWorkouts();
        const exercisesById = Object.fromEntries(exercises.map((exercise) => [exercise.id, exercise]));
        const sessions = getWorkoutSessions();
        const workoutLookup = new Map(workouts.map((workout) => [workout.id, workout]));
        const freshnessMapByCategory = sessions.reduce(
          (accumulator, session, index) => {
            const workout = workoutLookup.get(session.workoutId);
            const category = (workout?.category ?? session.workoutCategory) as Category | undefined;
            const subcategory = workout?.subcategory ?? session.workoutSubcategory;
            if (!category || !subcategory) return accumulator;
            const next = accumulator[category] ?? {};
            if (next[subcategory] === undefined) {
                            next[subcategory] = index + 1;
            }
            accumulator[category] = next;
            return accumulator;
          },
          {} as Record<Category, Record<string, number>>,
        );
        const usedWorkoutIds = new Set<string>();
        const weeklySubcategoryUsage: Record<Category, Record<string, number>> = {
          Basketball: {},
          Gym: {},
          Home: {},
          Regeneration: {},
        };
        const lastAssignedSubcategoryByCategory: Partial<Record<Category, string>> = {};
        const rawManual = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
        const rawManualByDate = rawManual ? (JSON.parse(rawManual) as Record<string, ManualDayWorkout[]>) : {};
        const manualByDate = dedupeManualMap(rawManualByDate);
        if (manualByDate !== rawManualByDate) {
          window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(manualByDate));
        }
        const disabledMap = readManualDayDisabledMap();
        const hiddenAutoMap = readHiddenAutoWorkoutsMap();
        setManualWorkoutsByDate(manualByDate);
        setDisabledManualDays(disabledMap);
        setHiddenAutoWorkoutsByDate(hiddenAutoMap);
        const manualByDay: Partial<Record<DayKey, ManualDayWorkout[]>> = {};
        weekdayOrder.forEach((index) => {
          const date = toLocalDateKey(getDateForWeekday(index));
          const dayKey = dayByIndex[index];
          const entries = manualByDate[date] ?? [];
          if (!entries.length) return;
          manualByDay[dayKey] = entries;
          entries.forEach((entry) => {
            const cat = entry.sport as Category;
            weeklySubcategoryUsage[cat] = {
              ...weeklySubcategoryUsage[cat],
              [entry.subcategory]: (weeklySubcategoryUsage[cat]?.[entry.subcategory] ?? 0) + 1,
            };
            lastAssignedSubcategoryByCategory[cat] = entry.subcategory;
          });
        });
        const dateKey = getTodayDateKey();
        const overrideWorkoutId = window.localStorage.getItem(`${WORKOUT_OVERRIDE_PREFIX}${dateKey}`);
        const overrideWorkout = overrideWorkoutId
          ? workouts.find((workout) => workout.id === overrideWorkoutId)
          : undefined;
        const avoidSubcategories: Partial<Record<Category, string[]>> = {};
        if (overrideWorkout) {
          usedWorkoutIds.add(overrideWorkout.id);
          avoidSubcategories[overrideWorkout.category] = [overrideWorkout.subcategory];
        }
        const coachingPriorities = buildBasketballCoachingPriorities(
          sessions,
          parsed.profile.favorite_position ?? "sg",
          parsed.playStyle,
          getProgressionState().level,
        );

        const suggested = {} as Record<DayKey, SuggestedWorkout>;
        const autoSuggested = {} as Record<DayKey, SuggestedWorkout>;
        computed.forEach((entry) => {
          const autoPick = selectBestWorkout(
            entry.sessionType,
            entry.day,
            entry.minutes,
            workouts,
            exercises,
            exercisesById,
            freshnessMapByCategory,
            usedWorkoutIds,
            weeklySubcategoryUsage,
            avoidSubcategories,
            parsed.profile.favorite_position ?? "sg",
            parsed.playStyle,
            lastAssignedSubcategoryByCategory,
            coachingPriorities,
          );

          autoSuggested[entry.day] = autoPick;

          const manualFirst = manualByDay[entry.day]?.[0];
          const manualFirstDuration = manualFirst
            ? manualFirst.durationMin
              ?? (manualFirst.exerciseIds?.length
                ? manualFirst.exerciseIds.reduce(
                    (sum, exerciseId) => sum + (exercisesById[exerciseId]?.durationMin ?? 10),
                    0,
                  )
                : entry.minutes)
            : entry.minutes;
          suggested[entry.day] = manualFirst
            ? {
                title: manualFirst.title ?? "Manuelles Workout",
                durationMin: manualFirstDuration,
                notes: manualFirst.notes || "Manuell geplant.",
                sport: manualFirst.sport ?? "Basketball",
                subcategory: manualFirst.subcategory ?? "-",
                exerciseIds: manualFirst.exerciseIds ?? [],
                exercises: (manualFirst.exerciseIds ?? [])
                  .map((exerciseId) => exercisesById[exerciseId]?.name)
                  .filter((name): name is string => Boolean(name)),
              }
            : autoPick;

          const usageSource = suggested[entry.day];
          const category = usageSource.sport as Category | undefined;
          if (!category || (category !== "Basketball" && category !== "Gym" && category !== "Home")) return;
          lastAssignedSubcategoryByCategory[category] = usageSource.subcategory;
        });

        if (overrideWorkout) {
          const todayKey = dayByIndex[todayIndex];
          const overrideSuggestion = {
            workoutId: overrideWorkout.id,
            title: overrideWorkout.name,
            durationMin: computeWorkoutDuration(overrideWorkout, exercisesById),
            notes: "Manuell für heute gewählt.",
            sport: overrideWorkout.category,
            subcategory: overrideWorkout.subcategory,
          };
          suggested[todayKey] = overrideSuggestion;
          autoSuggested[todayKey] = overrideSuggestion;
        }

        setSuggestionsByDay(suggested);
        setAutoSuggestionsByDay(autoSuggested);
      } catch {
        setPlannedEntries(null);
        setSuggestionsByDay(null);
        setAutoSuggestionsByDay(null);
        setManualWorkoutsByDate({});
      }
    }, 0);

    return () => window.clearTimeout(timer);
  }, [todayIndex, manualVersion, profileVersion]);

  useEffect(() => {
    const refreshProfilePlan = () => setProfileVersion((current) => current + 1);
    window.addEventListener("storage", refreshProfilePlan);
    window.addEventListener("focus", refreshProfilePlan);
    return () => {
      window.removeEventListener("storage", refreshProfilePlan);
      window.removeEventListener("focus", refreshProfilePlan);
    };
  }, []);

  useEffect(() => {
    const labels: Record<string, string> = {
      base: "Basis",
      build: "Aufbau",
      peak: "Peak",
      deload: "Deload",
    };
    const syncMesocycle = () => {
      const phase = loadTrainingGoalsBundle().mesocyclePhase ?? "build";
      setMesocycleLabel(labels[phase] ?? phase);
    };
    syncMesocycle();
    window.addEventListener("bt:training-goals-updated", syncMesocycle);
    return () => window.removeEventListener("bt:training-goals-updated", syncMesocycle);
  }, []);

  const regenSlotByDateKey = useMemo(() => {
    if (!suggestionsByDay || !autoSuggestionsByDay) return {};
    const out: Record<string, boolean> = {};
    for (const day of weekdayOrder) {
      const manualDateKey = toLocalDateKey(getDateForWeekday(day));
      const dayManualEntries = manualWorkoutsByDate[manualDateKey] ?? [];
      const hiddenCardIds = new Set(hiddenAutoWorkoutsByDate[manualDateKey] ?? []);
      const isDayDisabled = disabledManualDays[manualDateKey] === true;
      const headlineSuggested = suggestionsByDay[dayByIndex[day]] ?? null;
      const autoSuggestedWorkout = autoSuggestionsByDay[dayByIndex[day]] ?? null;
      out[manualDateKey] = weeklyRecoverySuggestionSlotVisible({
        manualDateKey,
        dayManualEntries,
        isDayDisabled,
        headlineSuggestedWorkout: headlineSuggested,
        autoSuggestedWorkout,
        hiddenCardIds,
      });
    }
    return out;
  }, [autoSuggestionsByDay, disabledManualDays, hiddenAutoWorkoutsByDate, manualWorkoutsByDate, suggestionsByDay]);

  useEffect(() => {
    if (!suggestionsByDay || !autoSuggestionsByDay) return;
    writeWeeklyRegenSlotMap(regenSlotByDateKey);
  }, [autoSuggestionsByDay, regenSlotByDateKey, suggestionsByDay]);

  const deleteManualWorkout = (dayIndex: (typeof weekdayOrder)[number], manualWorkoutId: string) => {
    const dateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const raw = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw) as Record<string, ManualDayWorkout[]>;
      const nextEntries = (parsed[dateKey] ?? []).filter((entry) => entry.id !== manualWorkoutId);
      const next = { ...parsed, [dateKey]: nextEntries };
      if (nextEntries.length === 0) {
        delete next[dateKey];
        const disabledMap = { ...readManualDayDisabledMap() };
        delete disabledMap[dateKey];
        writeManualDayDisabledMap(disabledMap);
        setDisabledManualDays(disabledMap);
      }
      window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(next));
      window.dispatchEvent(new Event("bt:plan-updated"));
      setManualWorkoutsByDate(next);
      setManualVersion((current) => current + 1);
    } catch {
      // noop
    }
  };
  const moveManualWorkoutToTomorrow = (dayIndex: (typeof weekdayOrder)[number], manualWorkoutId: string) => {
    const sourceDateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const sourceDate = new Date(`${sourceDateKey}T00:00:00`);
    sourceDate.setDate(sourceDate.getDate() + 1);
    const targetDateKey = toLocalDateKey(sourceDate);
    const raw = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw) as Record<string, ManualDayWorkout[]>;
      const currentEntries = parsed[sourceDateKey] ?? [];
      const moving = currentEntries.find((entry) => entry.id === manualWorkoutId);
      if (!moving) return;

      parsed[sourceDateKey] = currentEntries.filter((entry) => entry.id !== manualWorkoutId);
      if (parsed[sourceDateKey].length === 0) {
        delete parsed[sourceDateKey];
        const disabledMap = { ...readManualDayDisabledMap() };
        delete disabledMap[sourceDateKey];
        writeManualDayDisabledMap(disabledMap);
        setDisabledManualDays(disabledMap);
      }

      const existingTargetEntries = parsed[targetDateKey] ?? [];
      const targetHasSameId = existingTargetEntries.some((entry) => entry.id === moving.id);
      const movedEntry: ManualDayWorkout = targetHasSameId
        ? { ...moving, id: createManualEntryId() }
        : { ...moving };
      // Original-Dauer auf der Karte beibehalten – nicht an Ziel-Tag anpassen.
      if (movedEntry.durationMin == null && Array.isArray(movedEntry.exerciseIds) && movedEntry.exerciseIds.length > 0) {
        const exercisesById = Object.fromEntries(availableExercises.map((exercise) => [exercise.id, exercise]));
        const computed = movedEntry.exerciseIds.reduce(
          (sum, exerciseId) => sum + (exercisesById[exerciseId]?.durationMin ?? 10),
          0,
        );
        if (computed > 0) movedEntry.durationMin = computed;
      }
      parsed[targetDateKey] = dedupeManualEntries([movedEntry, ...existingTargetEntries]);

      const disabledMap = readManualDayDisabledMap();
      if (disabledMap[targetDateKey]) {
        const nextDisabled = { ...disabledMap };
        delete nextDisabled[targetDateKey];
        writeManualDayDisabledMap(nextDisabled);
        setDisabledManualDays(nextDisabled);
      }
      window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
      window.dispatchEvent(new Event("bt:plan-updated"));
      setManualWorkoutsByDate(parsed);
      setManualVersion((current) => current + 1);
    } catch {
      // noop
    }
  };

  const moveAutoWorkoutToTomorrow = (dayIndex: (typeof weekdayOrder)[number], selectedCard: WorkoutCardItem) => {
    const sourceDateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const sourceDate = new Date(`${sourceDateKey}T00:00:00`);
    sourceDate.setDate(sourceDate.getDate() + 1);
    const targetDateKey = toLocalDateKey(sourceDate);
    const raw = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    const parsed = raw ? (JSON.parse(raw) as Record<string, ManualDayWorkout[]>) : {};

    const isRecoveryCard = selectedCard.id.startsWith("recovery-") || selectedCard.sport === "Regeneration";
    const autoTitle = selectedCard.title.replace(/\s*\(.+\)\s*$/, "").trim();
    const targetEntries = parsed[targetDateKey] ?? [];

    const alreadyOnTarget = targetEntries.some(
      (entry) =>
        entry.title === autoTitle &&
        entry.sport === ((selectedCard.sport as ManualDayWorkout["sport"]) ?? "Basketball") &&
        entry.subcategory === selectedCard.subcategory,
    );

    if (!alreadyOnTarget) {
      const originalDuration = selectedCard.durationMin
        ?? selectedCard.autoSuggestion?.durationMin
        ?? null;
      const autoEntry: ManualDayWorkout = {
        id: createManualEntryId(),
        title: autoTitle,
        sport: (selectedCard.sport as ManualDayWorkout["sport"]) ?? "Basketball",
        subcategory: selectedCard.subcategory,
        notes: selectedCard.notes || "Aus Auto-Plan verschoben.",
        exerciseIds: selectedCard.autoSuggestion?.exerciseIds ?? [],
        durationMin: originalDuration ?? undefined,
      };
      parsed[targetDateKey] = dedupeManualEntries([autoEntry, ...targetEntries]);
    }

    window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
    window.dispatchEvent(new Event("bt:plan-updated"));

    // Karte vom Quell-Tag immer verstecken (auch Recovery), damit sie verschwindet.
    hideAutoWorkoutCard(dayIndex, selectedCard.id);

    if (!isRecoveryCard) {
      const sourceRecoveryCardId = `recovery-${sourceDateKey}`;
      const sourceHiddenMap = readHiddenAutoWorkoutsMap();
      const nextHiddenSource = { ...sourceHiddenMap };
      nextHiddenSource[sourceDateKey] = [
        ...new Set([...(nextHiddenSource[sourceDateKey] ?? []), sourceRecoveryCardId]),
      ];
      writeHiddenAutoWorkoutsMap(nextHiddenSource);
      setHiddenAutoWorkoutsByDate(nextHiddenSource);

      const targetHasRecovery = (parsed[targetDateKey] ?? []).some(
        (entry) => entry.sport === "Regeneration",
      );
      if (!targetHasRecovery) {
        const targetRecovery = buildRecoverySuggestion(dayByIndex[dayIndex], availableExercises);
        const recoveryEntry: ManualDayWorkout = {
          id: createManualEntryId(),
          title: targetRecovery.title,
          sport: "Regeneration",
          subcategory: targetRecovery.subcategory,
          notes: targetRecovery.notes,
          exerciseIds: targetRecovery.exerciseIds ?? [],
          durationMin: targetRecovery.durationMin,
        };
        parsed[targetDateKey] = dedupeManualEntries([...(parsed[targetDateKey] ?? []), recoveryEntry]);
        window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
      }
    }

    const disabledMap = readManualDayDisabledMap();
    if (disabledMap[targetDateKey]) {
      const nextDisabled = { ...disabledMap };
      delete nextDisabled[targetDateKey];
      writeManualDayDisabledMap(nextDisabled);
      setDisabledManualDays(nextDisabled);
    }

    setManualWorkoutsByDate(parsed);
    setManualVersion((current) => current + 1);
  };

  const disableDayAsNoTime = (dayIndex: (typeof weekdayOrder)[number]) => {
    const dateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const rawManual = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    if (rawManual) {
      try {
        const parsed = JSON.parse(rawManual) as Record<string, ManualDayWorkout[]>;
        delete parsed[dateKey];
        window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
        window.dispatchEvent(new Event("bt:plan-updated"));
        setManualWorkoutsByDate(parsed);
      } catch {
        // noop
      }
    }
    const hiddenMap = readHiddenAutoWorkoutsMap();
    if (hiddenMap[dateKey]) {
      const nextHidden = { ...hiddenMap };
      delete nextHidden[dateKey];
      writeHiddenAutoWorkoutsMap(nextHidden);
      setHiddenAutoWorkoutsByDate(nextHidden);
    }
    const disabledMap = { ...readManualDayDisabledMap(), [dateKey]: true };
    writeManualDayDisabledMap(disabledMap);
    setDisabledManualDays(disabledMap);
    const hasCompleted = completedDateSet.has(dateKey);
    if (isTodayOrFutureDate(dateKey) && !hasCompleted) {
      syncNoTimeForDate(dateKey);
    }
    setManualVersion((current) => current + 1);
  };

  const hideAutoWorkoutCard = (dayIndex: (typeof weekdayOrder)[number], cardId: string) => {
    const dateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const currentMap = readHiddenAutoWorkoutsMap();
    const hiddenForDate = new Set(currentMap[dateKey] ?? []);
    hiddenForDate.add(cardId);
    const nextMap = { ...currentMap, [dateKey]: Array.from(hiddenForDate) };
    writeHiddenAutoWorkoutsMap(nextMap);
    setHiddenAutoWorkoutsByDate(nextMap);
    const isRecoveryCard = cardId.startsWith("recovery-");
    const hasCompleted = completedDateSet.has(dateKey);
    if (!isRecoveryCard && isTodayOrFutureDate(dateKey) && !hasCompleted) {
      const disabledMap = { ...readManualDayDisabledMap(), [dateKey]: true };
      writeManualDayDisabledMap(disabledMap);
      setDisabledManualDays(disabledMap);
      syncNoTimeForDate(dateKey);
    }
    setSelectedWorkoutByDay((current) => ({ ...current, [dayByIndex[dayIndex]]: undefined }));
    setManualVersion((current) => current + 1);
  };

  return (
    <main className="app-container animate-in">
      <PageHeader
        eyebrow={mesocycleLabel ? `Mesozyklus · ${mesocycleLabel}` : "Wochenplan"}
        title="Weekly Workout"
        subtitle="Alle Tage sind direkt bearbeitbar – inklusive heute."
        actions={
          <>
            <Link href="/tips" className="btn btn-ghost btn-sm">Tipps &amp; Notizen</Link>
            <Link href="/stats" className="btn btn-ghost btn-sm">Spiel-Stats</Link>
          </>
        }
      />

      <div className="mt-3">
        <TopSubTabs items={[{ label: "Weekly", href: "/Weekly-Workout" }, { label: "Training", href: "/training" }]} />
      </div>

      <p className="mt-3 text-xs text-faint">Tipp: Wenn noch alles leer ist, im Profil zuerst Trainings-Tage und Schwerpunkte setzen.</p>

      <WeeklyBasketballCoach refreshKey={manualVersion + profileVersion} />

      <div className="mt-6 space-y-3">
        {orderedDays.map((day) => {
          const workout = WEEKLY_WORKOUT_PLAN[day];
          const profilePlan = plannedEntries?.find((entry) => entry.day === dayByIndex[day]) ?? null;
          const suggestedWorkout = suggestionsByDay?.[dayByIndex[day]] ?? null;
          const autoSuggestedWorkout = autoSuggestionsByDay?.[dayByIndex[day]] ?? null;
          const manualDateKey = toLocalDateKey(getDateForWeekday(day));
          const dayManualEntries = manualWorkoutsByDate[manualDateKey] ?? [];
          const hiddenCardIds = new Set(hiddenAutoWorkoutsByDate[manualDateKey] ?? []);
          const isDayDisabled = disabledManualDays[manualDateKey] === true;
          const hasManualWorkout = dayManualEntries.length > 0;
          const isRestDisplay = !hasManualWorkout && (isDayDisabled || (suggestedWorkout?.durationMin ?? 0) <= 0 || suggestedWorkout?.sport === "-");
                    const workoutCards: WorkoutCardItem[] = [];
          const shouldAddRecoveryCard =
            !isRestDisplay &&
            autoSuggestedWorkout?.sport !== "Regeneration" &&
            !storedRegenerationSignals(manualDateKey) &&
            dayManualEntries[0]?.sport !== "Rest";
          if (dayManualEntries.length > 0) {
            dayManualEntries.forEach((manualEntry) => {
              workoutCards.push({
                id: manualEntry.id,
                title: manualEntry.title,
                sport: manualEntry.sport,
                subcategory: manualEntry.subcategory,
                notes: manualEntry.notes || "Manuell geplant.",
                manualWorkoutId: manualEntry.id,
                durationMin: profilePlan?.minutes ?? suggestedWorkout?.durationMin ?? 0,
              });
            });
          }
          if (autoSuggestedWorkout && !isDayDisabled) {
            const autoWorkoutId = autoSuggestedWorkout.workoutId ?? buildAutoWorkoutId(day, autoSuggestedWorkout.sport);
            if (!hiddenCardIds.has(autoWorkoutId)) {
              workoutCards.push({
                id: autoWorkoutId,
                title: autoSuggestedWorkout.title,
                sport: autoSuggestedWorkout.sport,
                subcategory: autoSuggestedWorkout.subcategory,
                notes: autoSuggestedWorkout.notes,
                workoutId: autoWorkoutId,
                autoSuggestion: autoSuggestedWorkout.workoutId ? undefined : autoSuggestedWorkout,
                durationMin: autoSuggestedWorkout.durationMin,
              });
            }
          }
          if (shouldAddRecoveryCard) {
            const recoverySuggestion = buildRecoverySuggestion(dayByIndex[day], availableExercises);
            const recoveryCardId = `recovery-${manualDateKey}`;
            const recoveryWorkoutId = buildAutoWorkoutId(day, recoverySuggestion.sport);
            if (!hiddenCardIds.has(recoveryCardId)) {
              workoutCards.push({
                id: recoveryCardId,
                title: recoverySuggestion.title,
                sport: recoverySuggestion.sport,
                subcategory: recoverySuggestion.subcategory,
                notes: recoverySuggestion.notes,
                workoutId: recoveryWorkoutId,
                autoSuggestion: recoverySuggestion,
                durationMin: recoverySuggestion.durationMin,
              });
            }
          }
          const selectedCardId = selectedWorkoutByDay[dayByIndex[day]] ?? workoutCards[0]?.id;
          const selectedCard = workoutCards.find((entry) => entry.id === selectedCardId) ?? workoutCards[0] ?? null;
          const showTodayCompletionState = day === todayIndex;
          const completedIdsForDate = completedWorkoutIdsByDate[manualDateKey] ?? new Set<string>();
          const completedCardsCount = workoutCards.filter((card) => {
            if (card.manualWorkoutId) return completedIdsForDate.has(card.manualWorkoutId);
            if (card.workoutId) return completedIdsForDate.has(card.workoutId);
            return false;
          }).length;
          const isSelectedCardCompleted = Boolean(
            selectedCard &&
            ((selectedCard.manualWorkoutId && completedIdsForDate.has(selectedCard.manualWorkoutId)) ||
              (selectedCard.workoutId && completedIdsForDate.has(selectedCard.workoutId))),
          );
          const allCardsCompleted = workoutCards.length > 0 && completedCardsCount === workoutCards.length;
          const isSelectedCardInProgress = (() => {
            if (!selectedCard || typeof window === "undefined") return false;
            const selectedWorkoutId =
              selectedCard.manualWorkoutId ??
              selectedCard.workoutId ??
              selectedCard.autoSuggestion?.workoutId ??
              selectedCard.id;
            const fallbackProgress = getDefaultWorkoutProgress(manualDateKey, {
              id: selectedWorkoutId,
              title: selectedCard.title,
              sport: (selectedCard.sport as "Gym" | "Basketball" | "Home" | "Regeneration" | "Rest") ?? "Basketball",
              subcategory: selectedCard.subcategory,
              exercises: [],
            });
            const progress = parseWorkoutProgress(
              window.localStorage.getItem(buildWorkoutStorageKey(manualDateKey)),
              fallbackProgress,
            );
            return progress.status === "in_progress" && progress.workoutId === selectedWorkoutId;
          })();
          const startHref = (() => {
            if (!selectedCard) return `/workouts?day=${day}`;
            if (selectedCard.manualWorkoutId) return `/workouts?day=${day}&manualWorkoutId=${selectedCard.manualWorkoutId}`;
            const hasSyntheticId =
              selectedCard.workoutId?.startsWith("auto-") ||
              selectedCard.workoutId?.startsWith("recovery-");
            // Synthetische IDs (Recovery/Auto-Generated) haben kein echtes Workout im Katalog
            // → immer ueber autoSuggestion-Pfad gehen, sonst landet man auf dem Default-Wochenplan.
            if (selectedCard.autoSuggestion && (!selectedCard.workoutId || hasSyntheticId)) {
              const autoSuggestion = encodeAutoWorkoutSuggestion(selectedCard.autoSuggestion);
              return `/workouts?day=${day}${autoSuggestion ? `&autoWorkout=${autoSuggestion}` : ""}`;
            }
            if (selectedCard.workoutId && !hasSyntheticId) {
              return `/workouts?day=${day}&workoutId=${selectedCard.workoutId}`;
            }
            return `/workouts?day=${day}`;
          })();
          const editHref = selectedCard?.manualWorkoutId
            ? `/workouts?day=${day}&manual=1&manualWorkoutId=${selectedCard.manualWorkoutId}`
            : `/workouts?day=${day}&manual=1`;

          const dateLabel = getDateForWeekday(day).toLocaleDateString("de-DE", { day: "2-digit", month: "2-digit" });

          return (
            <article
              key={day}
              className={day === todayIndex ? "app-card app-card--today" : "app-card"}
            >
              <header className="flex items-center justify-between gap-3">
                <div>
                  <p className="section-eyebrow">{day === todayIndex ? "Heute" : dateLabel}</p>
                  <h3 className="mt-1 text-lg font-bold tracking-tight">{weekdayNames[day]}</h3>
                </div>
                <div className="flex flex-wrap items-center justify-end gap-1.5">
                  {showTodayCompletionState && allCardsCompleted ? (
                    <span className="chip chip-success">Alle erledigt ✅</span>
                  ) : null}
                  {profilePlan ? (
                    <span className="chip">{profilePlan.minutes} Min</span>
                  ) : null}
                </div>
              </header>

              <p className="mt-3 text-base font-semibold text-strong">
                {isRestDisplay ? "Frei · Kein Workout geplant" : selectedCard?.title ?? suggestedWorkout?.title ?? workout.title}
              </p>
              {profilePlan ? (
                <p className="mt-1 text-xs text-muted">
                  Profil-Plan: <span className="text-strong">{profilePlan.sessionType}</span> · {profilePlan.intensity}
                </p>
              ) : null}

              <div className="mt-4 grid gap-2 md:grid-cols-2">
                {workoutCards.length > 0 && !isRestDisplay ? workoutCards.map((card, cardIndex) => {
                  const isDone = showTodayCompletionState &&
                    ((card.manualWorkoutId && completedIdsForDate.has(card.manualWorkoutId)) ||
                      (card.workoutId && completedIdsForDate.has(card.workoutId)));
                  const isSelected = selectedCardId === card.id;
                  return (
                    <button
                      key={`${day}-${card.id}-${cardIndex}`}
                      type="button"
                      onClick={() =>
                        setSelectedWorkoutByDay((current) => ({
                          ...current,
                          [dayByIndex[day]]: card.id,
                        }))
                      }
                      className={`rounded-2xl border p-3 text-left transition ${
                        isDone
                          ? "border-emerald-500/55 bg-emerald-500/10"
                          : isSelected
                            ? "border-orange-400/70 bg-orange-500/10"
                            : "border-white/10 bg-white/[0.03] hover:border-white/20 hover:bg-white/[0.06]"
                      }`}
                    >
                      <p className="flex items-center gap-2 font-semibold text-strong">
                        <span className="truncate">{card.title}</span>
                        {isDone ? <span className="text-emerald-300">✅</span> : null}
                      </p>
                      <p className="mt-1 text-xs text-muted">{card.sport} · {card.subcategory}</p>
                      <p className="mt-0.5 text-xs text-faint">{card.durationMin} Min</p>
                    </button>
                  );
                }) : (
                  <p className="rounded-2xl border border-white/10 bg-white/[0.02] p-3 text-xs text-muted">
                    {isRestDisplay
                      ? "Tag ist als Frei markiert. Versuche heute trotzdem eine kleine Aktivität 🙌"
                      : "Kein Workout hinterlegt."}
                  </p>
                )}
              </div>

              {selectedCard && !isRestDisplay ? (
                <div className="mt-3 flex flex-wrap gap-2 rounded-2xl border border-white/10 bg-white/[0.02] p-2">
                  {(selectedCard.subcategory === "Spiel" || selectedCard.subcategory === "Spieltraining") ? (
                    <Link
                      href={`/game-track?date=${manualDateKey}&context=${selectedCard.subcategory === "Spieltraining" ? "game_training" : "game"}`}
                      className="btn btn-violet btn-xs"
                    >
                      Spiel tracken
                    </Link>
                  ) : null}
                  <Link href={startHref} className="btn btn-primary btn-xs">
                    {showTodayCompletionState && isSelectedCardCompleted
                      ? "Workout ansehen"
                      : isSelectedCardInProgress
                        ? "Workout bearbeiten"
                        : "Workout starten"}
                  </Link>
                  <Link href={editHref} className="btn btn-outline btn-xs">
                    Bearbeiten
                  </Link>
                  <Link href={`/workouts?day=${day}&manual=1`} className="btn btn-emerald btn-xs">
                    Hinzufügen
                  </Link>
                  <button
                    type="button"
                    onClick={() => {
                      if (selectedCard.manualWorkoutId) {
                        deleteManualWorkout(day, selectedCard.manualWorkoutId);
                        return;
                      }
                      hideAutoWorkoutCard(day, selectedCard.id);
                    }}
                    className="btn btn-danger-outline btn-xs"
                  >
                    {selectedCard.manualWorkoutId ? "Löschen" : "Ausblenden"}
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      if (selectedCard.manualWorkoutId) {
                        moveManualWorkoutToTomorrow(day, selectedCard.manualWorkoutId);
                        return;
                      }
                      moveAutoWorkoutToTomorrow(day, selectedCard);
                    }}
                    className="btn btn-cyan btn-xs"
                  >
                    Auf morgen
                  </button>
                  <button
                    type="button"
                    onClick={() => disableDayAsNoTime(day)}
                    className="btn btn-ghost btn-xs"
                  >
                    Keine Zeit
                  </button>
                </div>
              ) : null}

              {!selectedCard || isRestDisplay ? (
                <div className="mt-3 flex flex-wrap gap-2">
                  <Link href={`/workouts?day=${day}&manual=1`} className="btn btn-emerald btn-xs">
                    Workout hinzufügen
                  </Link>
                  {!isRestDisplay ? null : (
                    <button
                      type="button"
                      onClick={() => disableDayAsNoTime(day)}
                      className="btn btn-ghost btn-xs"
                    >
                      Frei bestätigen
                    </button>
                  )}
                </div>
              ) : null}

              {selectedCard && !isRestDisplay ? (
                <p className="mt-3 text-xs text-faint">{selectedCard.notes}</p>
              ) : isRestDisplay ? (
                <p className="mt-3 text-xs text-emerald-300">
                  {REST_QUOTES[(day + new Date().getDate()) % REST_QUOTES.length]}
                </p>
              ) : (
                <ul className="mt-3 space-y-1 text-sm text-muted">
                  {workout.exercises.map((exercise) => (
                    <li key={`${workout.id}-${exercise.name}`} className="flex gap-2">
                      <span aria-hidden className="mt-1 h-1 w-1 shrink-0 rounded-full bg-white/30" />
                      <span>{exercise.name}</span>
                    </li>
                  ))}
                </ul>
              )}
            </article>
          );
        })}
      </div>
    </main>
  );
}
