"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { type Category, type Exercise, type Workout } from "@/lib/training-data";
import { getWorkoutSessions } from "@/lib/session-storage";
import { loadExercises, loadWorkouts } from "@/lib/training-storage";
import {
  WORKOUT_OVERRIDE_PREFIX,
  WEEKLY_WORKOUT_PLAN,
  getDateForWeekday,
  getTodayDateKey,
  toLocalDateKey,
} from "@/lib/workout";
import { buildWeeklyPlan, type DayKey, type WeekConfig } from "@/lib/planner";
import {
  buildGeneratedWorkout,
  getFocusProfile,
  pickSubcategoryForDay,
} from "@/lib/player-workout-engine";
import {
  MANUAL_DAY_WORKOUTS_KEY,
  readDailyPlanMap,
  readManualDayDisabledMap,
  type PlannedWorkoutTag,
  writeManualDayDisabledMap,
} from "@/lib/activity-calendar";

const weekdayOrder = [1, 2, 3, 4, 5, 6, 0] as const;

const weekdayNames: Record<(typeof weekdayOrder)[number], string> = {
  0: "Sonntag",
  1: "Montag",
  2: "Dienstag",
  3: "Mittwoch",
  4: "Donnerstag",
  5: "Freitag",
  6: "Samstag",
};

const dayByIndex: Record<(typeof weekdayOrder)[number], DayKey> = {
  0: "sunday",
  1: "monday",
  2: "tuesday",
  3: "wednesday",
  4: "thursday",
  5: "friday",
  6: "saturday",
};
type ManualDayWorkout = {
  id: string;
  title: string;
  sport: "Basketball" | "Gym" | "Home" | "Rest";
  subcategory: string;
  notes: string;
  exerciseIds: string[];
};
const TAG_TO_SPORT: Partial<Record<PlannedWorkoutTag, "Basketball" | "Gym" | "Home" | "-">> = {
  Spieltag: "Basketball",
  Trainingstag: "Basketball",
  Spieltraining: "Basketball",
  Gym: "Gym",
  "Home-Workout": "Home",
  Regeneration: "-",
};

type ProfileLocalCache = {
  profile: {
    favorite_position: string | null;
  };
  playStyle: string;
  weekConfig: WeekConfig;
  weeklyGoalSessions: number;
};

type PlannedUiEntry = {
  day: DayKey;
  sessionType: string;
  intensity: string;
  minutes: number;
  reason: string;
};

type SuggestedWorkout = {
  workoutId?: string;
  title: string;
  durationMin: number;
  notes: string;
  sport: string;
  subcategory: string;
  exerciseIds?: string[];
  exercises?: string[];
  isAutoGenerated?: boolean;
};

type WorkoutCardItem = {
  id: string;
  title: string;
  sport: string;
  subcategory: string;
  notes: string;
  workoutId?: string;
  autoSuggestion?: SuggestedWorkout;
  manualWorkoutId?: string;
  durationMin: number;
};


function encodeAutoWorkoutSuggestion(suggestion: SuggestedWorkout) {
  const payload = {
    title: suggestion.title,
    sport: suggestion.sport,
    subcategory: suggestion.subcategory,
    notes: suggestion.notes,
    exerciseIds: suggestion.exerciseIds ?? [],
    exercises: suggestion.exercises ?? [],
  };

  try {
    return encodeURIComponent(JSON.stringify(payload));
  } catch {
    return null;
  }
}

function roundUpToNearestFive(value: number) {
  return Math.ceil(value / 5) * 5;
}

function normalizeExerciseFamily(name: string) {
  return name
    .toLowerCase()
    .replace(/\s*-\s*(rechts|links|right|left)\b/g, "")
    .replace(/\s*[-–]?\s*\d+\s*$/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function buildRelatedExerciseNames(
  workout: Workout,
  exercises: Exercise[],
  exercisesById: Record<string, Exercise>,
) {
  const baseExercises = workout.exerciseIds
    .map((exerciseId) => exercisesById[exerciseId])
    .filter((exercise): exercise is Exercise => Boolean(exercise));
  const familyKeys = new Set(baseExercises.map((exercise) => normalizeExerciseFamily(exercise.name)));
  const related = exercises.filter(
    (exercise) =>
      exercise.category === workout.category &&
      exercise.subcategory === workout.subcategory &&
      familyKeys.has(normalizeExerciseFamily(exercise.name)),
  );
  const mergedNames = [...baseExercises.map((exercise) => exercise.name), ...related.map((exercise) => exercise.name)];
  return [...new Set(mergedNames)];
}

function getSeedIndex(seedSource: string, length: number) {
  if (length <= 0) return 0;
  let hash = 0;
  for (let i = 0; i < seedSource.length; i += 1) {
    hash = (hash * 31 + seedSource.charCodeAt(i)) >>> 0;
  }
  return hash % length;
}

function computeWorkoutDuration(workout: Workout, exercisesById: Record<string, Exercise>) {
  const rawDuration = workout.exerciseIds.reduce((sum, exerciseId) => {
    const exercise = exercisesById[exerciseId];
    return sum + (exercise?.durationMin ?? 10);
  }, 0);

  return roundUpToNearestFive(rawDuration * 1.1);
}

function buildFallbackSuggestion(mode: string, minutes: number): SuggestedWorkout | null {
  if (mode === "none" || mode === "recovery" || minutes <= 0) {
    return {
      title: "Freier Tag",
      durationMin: 0,
      notes: "Heute ist ein freier Tag. Versuche trotzdem eine kleine aktive Gewohnheit zu schaffen 💪",
      sport: "-",
      subcategory: "Frei",
    };
  }

  if (mode === "game") {
    return {
      title: "Spieltag",
      durationMin: minutes,
      notes: "Nur Match-Fokus, kein zusätzliches Workout.",
      sport: "Basketball",
      subcategory: "Game",
    };
  }

  return null;
}

function buildRecoverySuggestion(day: DayKey, exercises: Exercise[]): SuggestedWorkout {
  const generated = buildGeneratedWorkout({
    day,
    category: "Regeneration",
    subcategory: "Mobilität & Dehnung",
    targetMinutes: 15,
    exercisePool: exercises,
  });
  return {
    title: generated.name,
    durationMin: generated.durationMin,
    notes: `Kurz-Recovery: ${generated.notes}`,
    sport: generated.category,
    subcategory: generated.subcategory,
    exerciseIds: generated.exerciseIds,
    exercises: generated.exerciseNames,
    isAutoGenerated: true,
  };
}

function syncNoTimeForDate(dateKey: string) {
  const dailyRaw = window.localStorage.getItem("bt.daily-plan.v1");
  const dailyPlan = dailyRaw ? (JSON.parse(dailyRaw) as Record<string, PlannedWorkoutTag[]>) : {};
  dailyPlan[dateKey] = [];
  window.localStorage.setItem("bt.daily-plan.v1", JSON.stringify(dailyPlan));

  const parsedDate = new Date(`${dateKey}T00:00:00`);
  const dayMap: Record<number, DayKey> = {
    0: "sunday",
    1: "monday",
    2: "tuesday",
    3: "wednesday",
    4: "thursday",
    5: "friday",
    6: "saturday",
  };
  const targetDay = dayMap[parsedDate.getDay()];
  const rawProfile = window.localStorage.getItem("profile_cache_v4");
  if (!rawProfile) return;
  try {
    const parsed = JSON.parse(rawProfile) as { weekConfig?: Partial<Record<DayKey, { mode: string; minutes: number }>> };
    parsed.weekConfig = {
      ...(parsed.weekConfig ?? {}),
      [targetDay]: { mode: "unavailable", minutes: 0 },
    };
    window.localStorage.setItem("profile_cache_v4", JSON.stringify(parsed));
  } catch {
    // noop
  }
}

function selectBestWorkout(
  mode: string,
  day: DayKey,
  targetMinutes: number,
  workouts: Workout[],
  exercises: Exercise[],
  exercisesById: Record<string, Exercise>,
  freshnessMapByCategory: Record<Category, Record<string, number>>,
  usedWorkoutIds: Set<string>,
  weeklySubcategoryUsage: Record<Category, Record<string, number>>,
  avoidSubcategories: Partial<Record<Category, string[]>>,
  position: string,
  playStyle: string,
  lastAssignedSubcategoryByCategory: Partial<Record<Category, string>>,
): SuggestedWorkout {
  const targetWithExtra = targetMinutes;
  const modeLabel = mode === "game-training" ? "Spieltraining (15 Min vorab + 30 Min danach)" : "Direktes Training";
  if (mode === "recovery") {
    return buildRecoverySuggestion(day, exercises);
  }
  const fallback = buildFallbackSuggestion(mode, targetWithExtra);
  if (fallback) return fallback;

  const desiredCategory: Category =
    mode === "gym" ? "Gym" : "Basketball";
  const focusProfile = getFocusProfile({ position, playStyle });

  const categoryFreshness = freshnessMapByCategory[desiredCategory] ?? {};
  const subcategoryRank = (subcategory: string) => categoryFreshness[subcategory] ?? 0;
  const weeklyUsage = weeklySubcategoryUsage[desiredCategory] ?? {};
  const subcategoryWeeklyCount = (subcategory: string) => weeklyUsage[subcategory] ?? 0;

  const filteredByCategory = workouts.filter((workout) => workout.category === desiredCategory);
  const availableSubcategories = [
    ...new Set(
      filteredByCategory.map((workout) => workout.subcategory),
    ),
  ];
  const preferredSubcategory = pickSubcategoryForDay({
    category: desiredCategory,
    focusProfile,
    usage: weeklySubcategoryUsage[desiredCategory] ?? {},
    availableSubcategories,
  });
  if (filteredByCategory.length === 0) {
    const generated = buildGeneratedWorkout({
      day,
      category: desiredCategory,
      subcategory: desiredCategory,
      targetMinutes: roundUpToNearestFive(targetWithExtra),
      exercisePool: exercises,
    });
    return {
      title: generated.name,
      durationMin: generated.durationMin,
      notes: generated.notes,
      sport: generated.category,
      subcategory: generated.subcategory,
      exerciseIds: generated.exerciseIds,
      exercises: generated.exerciseNames,
      isAutoGenerated: true,
    };
  }

  const filtered = filteredByCategory
    .map((workout) => ({
      workout,
      duration: computeWorkoutDuration(workout, exercisesById),
    }))
    .sort((left, right) => {
      if (left.workout.subcategory === preferredSubcategory && right.workout.subcategory !== preferredSubcategory) {
        return -1;
      }
      if (right.workout.subcategory === preferredSubcategory && left.workout.subcategory !== preferredSubcategory) {
        return 1;
      }
      return 0;
    });
  const unusedPool = filtered.filter((entry) => !usedWorkoutIds.has(entry.workout.id));
  const avoidForCategory = avoidSubcategories[desiredCategory] ?? [];
  const withoutAvoidedSubcategories = unusedPool.filter(
    (entry) => !avoidForCategory.includes(entry.workout.subcategory),
  );
  const pool =
    withoutAvoidedSubcategories.length > 0
      ? withoutAvoidedSubcategories
      : unusedPool.length > 0
        ? unusedPool
        : [];
  const nonConsecutivePool = pool.filter(
    (entry) => entry.workout.subcategory !== lastAssignedSubcategoryByCategory[desiredCategory],
  );
  const dayPool = nonConsecutivePool.length > 0 ? nonConsecutivePool : pool;

  if (dayPool.length === 0) {
    const generated = buildGeneratedWorkout({
      day,
      category: desiredCategory,
      subcategory: preferredSubcategory,
      targetMinutes: targetWithExtra,
      exercisePool: exercises,
    });
    weeklySubcategoryUsage[desiredCategory] = {
      ...weeklySubcategoryUsage[desiredCategory],
      [generated.subcategory]:
        (weeklySubcategoryUsage[desiredCategory]?.[generated.subcategory] ?? 0) + 1,
    };
    return {
      title: generated.name,
      durationMin: generated.durationMin,
      notes: `${modeLabel}: ${generated.notes} (keine duplizierten Workouts in dieser Woche).`,
      sport: generated.category,
      subcategory: generated.subcategory,
      exerciseIds: generated.exerciseIds,
      exercises: generated.exerciseNames,
      isAutoGenerated: true,
    };
  }

  const compliantPool = dayPool.filter(
    (entry) =>
      (weeklySubcategoryUsage[desiredCategory]?.[entry.workout.subcategory] ?? 0) <
      (desiredCategory === "Gym" ? 2 : 2),
  );
  const effectivePool = compliantPool.length > 0 ? compliantPool : dayPool;

  const sortedPool = [...effectivePool].sort((a, b) => {
    const weeklyDiff = subcategoryWeeklyCount(a.workout.subcategory) - subcategoryWeeklyCount(b.workout.subcategory);
    if (weeklyDiff !== 0) return weeklyDiff;

    const freshnessDiff = subcategoryRank(a.workout.subcategory) - subcategoryRank(b.workout.subcategory);
    if (freshnessDiff !== 0) return freshnessDiff;

    const durationDiff = Math.abs(a.duration - targetWithExtra) - Math.abs(b.duration - targetWithExtra);
    if (durationDiff !== 0) return durationDiff;

    const aSeed = getSeedIndex(`${day}-${a.workout.id}`, 97);
    const bSeed = getSeedIndex(`${day}-${b.workout.id}`, 97);
    return aSeed - bSeed;
  });
  const best = sortedPool[0];

  const shouldGenerateWorkout =
    best.workout.subcategory !== preferredSubcategory &&
    (weeklySubcategoryUsage[desiredCategory]?.[preferredSubcategory] ?? 0) <
      (desiredCategory === "Gym" ? 2 : 2);

  if (shouldGenerateWorkout) {
    const generated = buildGeneratedWorkout({
      day,
      category: desiredCategory,
      subcategory: preferredSubcategory,
      targetMinutes: targetWithExtra,
      exercisePool: exercises,
    });
    weeklySubcategoryUsage[desiredCategory] = {
      ...weeklySubcategoryUsage[desiredCategory],
      [generated.subcategory]:
        (weeklySubcategoryUsage[desiredCategory]?.[generated.subcategory] ?? 0) + 1,
    };
    return {
      title: generated.name,
      durationMin: generated.durationMin,
      notes: `${modeLabel}: ${generated.notes} Fokus via Spielertyp-Mapping.`,
      sport: generated.category,
      subcategory: generated.subcategory,
      exerciseIds: generated.exerciseIds,
      exercises: generated.exerciseNames,
      isAutoGenerated: true,
    };
  }

  usedWorkoutIds.add(best.workout.id);
  weeklySubcategoryUsage[desiredCategory] = {
    ...weeklySubcategoryUsage[desiredCategory],
    [best.workout.subcategory]: subcategoryWeeklyCount(best.workout.subcategory) + 1,
  };

  return {
    workoutId: best.workout.id,
    title: best.workout.name,
    durationMin: best.duration,
    notes: `${modeLabel}: Match zu ${targetWithExtra} Min (${best.workout.category} • ${best.workout.subcategory})`,
    sport: best.workout.category,
    subcategory: best.workout.subcategory,
    exerciseIds: best.workout.exerciseIds,
    exercises: buildRelatedExerciseNames(best.workout, exercises, exercisesById),
  };
}

export default function WeeklyWorkoutPage() {
  const todayIndex = new Date().getDay() as (typeof weekdayOrder)[number];
  const orderedDays = useMemo(
    () => [...weekdayOrder]
      .sort((left, right) => ((left - todayIndex + 7) % 7) - ((right - todayIndex + 7) % 7)),
    [todayIndex],
  );
  const [plannedEntries, setPlannedEntries] = useState<PlannedUiEntry[] | null>(null);
  const [suggestionsByDay, setSuggestionsByDay] = useState<Record<DayKey, SuggestedWorkout> | null>(null);
  const [manualWorkoutsByDate, setManualWorkoutsByDate] = useState<Record<string, ManualDayWorkout[]>>({});
  const [selectedWorkoutByDay, setSelectedWorkoutByDay] = useState<Partial<Record<DayKey, string>>>({});
  const [manualVersion, setManualVersion] = useState(0);
  const [dailyPlanMap, setDailyPlanMap] = useState<Record<string, PlannedWorkoutTag[]>>({});
  const [disabledManualDays, setDisabledManualDays] = useState<Record<string, boolean>>({});
  const availableExercises = useMemo(() => loadExercises(), []);
  const completedDateSet = new Set(getWorkoutSessions().map((session) => toLocalDateKey(new Date(session.dateISO))));

  useEffect(() => {
    const timer = window.setTimeout(() => {
      const raw = window.localStorage.getItem("profile_cache_v4");
      if (!raw) return;

      try {
        const parsed = JSON.parse(raw) as ProfileLocalCache;
        const computed = buildWeeklyPlan({
          position: parsed.profile.favorite_position ?? "sg",
          playStyle: parsed.playStyle,
          weekConfig: parsed.weekConfig,
          weeklyGoalSessions: parsed.weeklyGoalSessions,
        });

        setPlannedEntries(computed);

        const exercises = loadExercises();
        const workouts = loadWorkouts();
        const exercisesById = Object.fromEntries(exercises.map((exercise) => [exercise.id, exercise]));
        const sessions = getWorkoutSessions();
        const workoutLookup = new Map(workouts.map((workout) => [workout.id, workout]));
        const freshnessMapByCategory = sessions.reduce(
          (accumulator, session, index) => {
            const workout = workoutLookup.get(session.workoutId);
            const category = (workout?.category ?? session.workoutCategory) as Category | undefined;
            const subcategory = workout?.subcategory ?? session.workoutSubcategory;
            if (!category || !subcategory) return accumulator;
            const next = accumulator[category] ?? {};
            if (next[subcategory] === undefined) {
              next[subcategory] = index + 1;
            }
            accumulator[category] = next;
            return accumulator;
          },
          {} as Record<Category, Record<string, number>>,
        );
        const usedWorkoutIds = new Set<string>();
        const weeklySubcategoryUsage: Record<Category, Record<string, number>> = {
          Basketball: {},
          Gym: {},
          Home: {},
        };
        const lastAssignedSubcategoryByCategory: Partial<Record<Category, string>> = {};
        const rawManual = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
        const manualByDate = rawManual ? (JSON.parse(rawManual) as Record<string, ManualDayWorkout[]>) : {};
        const disabledMap = readManualDayDisabledMap();
        setManualWorkoutsByDate(manualByDate);
        setDisabledManualDays(disabledMap);
        const manualByDay: Partial<Record<DayKey, ManualDayWorkout[]>> = {};
        weekdayOrder.forEach((index) => {
          const date = toLocalDateKey(getDateForWeekday(index));
          const dayKey = dayByIndex[index];
          const entries = manualByDate[date] ?? [];
          if (!entries.length) return;
          manualByDay[dayKey] = entries;
          entries.forEach((entry) => {
            const cat = entry.sport as Category;
            weeklySubcategoryUsage[cat] = {
              ...weeklySubcategoryUsage[cat],
              [entry.subcategory]: (weeklySubcategoryUsage[cat]?.[entry.subcategory] ?? 0) + 1,
            };
            lastAssignedSubcategoryByCategory[cat] = entry.subcategory;
          });
        });
        const dateKey = getTodayDateKey();
        const overrideWorkoutId = window.localStorage.getItem(`${WORKOUT_OVERRIDE_PREFIX}${dateKey}`);
        const overrideWorkout = overrideWorkoutId
          ? workouts.find((workout) => workout.id === overrideWorkoutId)
          : undefined;
        const avoidSubcategories: Partial<Record<Category, string[]>> = {};
        if (overrideWorkout) {
          usedWorkoutIds.add(overrideWorkout.id);
          avoidSubcategories[overrideWorkout.category] = [overrideWorkout.subcategory];
        }
        const suggested = {} as Record<DayKey, SuggestedWorkout>;
        computed.forEach((entry) => {
          const nextSuggestion = manualByDay[entry.day]?.[0]
            ? {
                title: manualByDay[entry.day]?.[0]?.title ?? "Manuelles Workout",
                durationMin: entry.minutes,
                notes: manualByDay[entry.day]?.[0]?.notes || "Manuell geplant.",
                sport: manualByDay[entry.day]?.[0]?.sport ?? "Basketball",
                subcategory: manualByDay[entry.day]?.[0]?.subcategory ?? "-",
                exerciseIds: manualByDay[entry.day]?.[0]?.exerciseIds ?? [],
                exercises: (manualByDay[entry.day]?.[0]?.exerciseIds ?? [])
                  .map((exerciseId) => exercisesById[exerciseId]?.name)
                  .filter((name): name is string => Boolean(name)),
              }
            : selectBestWorkout(
                entry.sessionType,
                entry.day,
                entry.minutes,
                workouts,
                exercises,
                exercisesById,
                freshnessMapByCategory,
                usedWorkoutIds,
                weeklySubcategoryUsage,
                avoidSubcategories,
                parsed.profile.favorite_position ?? "sg",
                parsed.playStyle,
                lastAssignedSubcategoryByCategory,
              );

          suggested[entry.day] = nextSuggestion;
          const category = nextSuggestion.sport as Category | undefined;
          if (!category || (category !== "Basketball" && category !== "Gym" && category !== "Home")) return;
          lastAssignedSubcategoryByCategory[category] = nextSuggestion.subcategory;
        });

        if (overrideWorkout) {
          const todayKey = dayByIndex[todayIndex];
          suggested[todayKey] = {
            workoutId: overrideWorkout.id,
            title: overrideWorkout.name,
            durationMin: computeWorkoutDuration(overrideWorkout, exercisesById),
            notes: "Manuell für heute gewählt.",
            sport: overrideWorkout.category,
            subcategory: overrideWorkout.subcategory,
          };
        }

        setSuggestionsByDay(suggested);
      } catch {
        setPlannedEntries(null);
        setSuggestionsByDay(null);
        setManualWorkoutsByDate({});
      }
    }, 0);

    return () => window.clearTimeout(timer);
  }, [todayIndex, manualVersion]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setDailyPlanMap(readDailyPlanMap());
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);

  const deleteManualWorkout = (dayIndex: (typeof weekdayOrder)[number], manualWorkoutId: string) => {
    const dateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const raw = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw) as Record<string, ManualDayWorkout[]>;
      const nextEntries = (parsed[dateKey] ?? []).filter((entry) => entry.id !== manualWorkoutId);
      const next = { ...parsed, [dateKey]: nextEntries };
      if (nextEntries.length === 0) {
        delete next[dateKey];
        const disabledMap = { ...readManualDayDisabledMap(), [dateKey]: true };
        writeManualDayDisabledMap(disabledMap);
        setDisabledManualDays(disabledMap);
        const isToday = dateKey === getTodayDateKey();
        const hasCompletedToday = completedDateSet.has(dateKey);
        if (isToday && !hasCompletedToday) {
          syncNoTimeForDate(dateKey);
          setDailyPlanMap(readDailyPlanMap());
        }
      }
      window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(next));
      setManualWorkoutsByDate(next);
      setManualVersion((current) => current + 1);
    } catch {
      // noop
    }
  };
  const deleteAllManualWorkouts = (dayIndex: (typeof weekdayOrder)[number]) => {
    const dateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const raw = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw) as Record<string, ManualDayWorkout[]>;
      delete parsed[dateKey];
      window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
      const disabledMap = { ...readManualDayDisabledMap(), [dateKey]: true };
      writeManualDayDisabledMap(disabledMap);
      setDisabledManualDays(disabledMap);
      const isToday = dateKey === getTodayDateKey();
      const hasCompletedToday = completedDateSet.has(dateKey);
      if (isToday && !hasCompletedToday) {
        syncNoTimeForDate(dateKey);
        setDailyPlanMap(readDailyPlanMap());
      }
      setManualWorkoutsByDate(parsed);
      setManualVersion((current) => current + 1);
    } catch {
      // noop
    }
  };
  const moveManualWorkoutToTomorrow = (dayIndex: (typeof weekdayOrder)[number], manualWorkoutId: string) => {
    const sourceDateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const sourceDate = new Date(`${sourceDateKey}T00:00:00`);
    sourceDate.setDate(sourceDate.getDate() + 1);
    const targetDateKey = toLocalDateKey(sourceDate);
    const raw = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw) as Record<string, ManualDayWorkout[]>;
      const currentEntries = parsed[sourceDateKey] ?? [];
      const moving = currentEntries.find((entry) => entry.id === manualWorkoutId);
      if (!moving) return;
      parsed[sourceDateKey] = currentEntries.filter((entry) => entry.id !== manualWorkoutId);
      if (parsed[sourceDateKey].length === 0) delete parsed[sourceDateKey];
      parsed[targetDateKey] = [moving, ...(parsed[targetDateKey] ?? [])];
      window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
      setManualWorkoutsByDate(parsed);
      setManualVersion((current) => current + 1);
    } catch {
      // noop
    }
  };

  return (
    <main className="min-h-screen bg-black p-6 pb-24 text-white">
      <h1 className="text-2xl font-bold">Weekly Workout Plan</h1>
      <p className="mt-2 text-zinc-400">Alle Tage sind direkt bearbeitbar – inklusive heute.</p>

      <div className="mt-6 space-y-3">
        {orderedDays.map((day) => {
          const workout = WEEKLY_WORKOUT_PLAN[day];
          const profilePlan = plannedEntries?.find((entry) => entry.day === dayByIndex[day]) ?? null;
          const suggestedWorkout = suggestionsByDay?.[dayByIndex[day]] ?? null;
          const manualDateKey = toLocalDateKey(getDateForWeekday(day));
          const dayManualEntries = manualWorkoutsByDate[manualDateKey] ?? [];
          const isDayDisabled = disabledManualDays[manualDateKey] === true;
          const plannedTags = dailyPlanMap[manualDateKey] ?? [];
          const isRestDisplay = isDayDisabled || (suggestedWorkout?.durationMin ?? 0) <= 0 || suggestedWorkout?.sport === "-";
          const primaryManual = dayManualEntries[0];
          const workoutCards: WorkoutCardItem[] = [];
          const shouldAddRecoveryCard =
            !isRestDisplay &&
            !plannedTags.includes("Regeneration") &&
            primaryManual?.sport !== "Rest";
          if (primaryManual) {
            workoutCards.push({
              id: primaryManual.id,
              title: primaryManual.title,
              sport: primaryManual.sport,
              subcategory: primaryManual.subcategory,
              notes: primaryManual.notes || "Manuell geplant.",
              manualWorkoutId: primaryManual.id,
              durationMin: profilePlan?.minutes ?? suggestedWorkout?.durationMin ?? 0,
            });
          } else if (suggestedWorkout && !isDayDisabled) {
            workoutCards.push({
              id: suggestedWorkout.workoutId ?? `auto-${day}`,
              title: suggestedWorkout.title,
              sport: suggestedWorkout.sport,
              subcategory: suggestedWorkout.subcategory,
              notes: suggestedWorkout.notes,
              workoutId: suggestedWorkout.workoutId,
              autoSuggestion: suggestedWorkout.workoutId ? undefined : suggestedWorkout,
              durationMin: suggestedWorkout.durationMin,
            });
          } else if (plannedTags.length > 0) {
            const primaryTag = plannedTags[0];
            workoutCards.push({
              id: `planned-${manualDateKey}`,
              title: primaryTag,
              sport: TAG_TO_SPORT[primaryTag] ?? "Basketball",
              subcategory: plannedTags.slice(1).join(", ") || primaryTag,
              notes: `Geplant: ${plannedTags.join(", ")}`,
              durationMin: profilePlan?.minutes ?? 0,
            });
          }
          if (shouldAddRecoveryCard) {
            const recoverySuggestion = buildRecoverySuggestion(dayByIndex[day], availableExercises);
            workoutCards.push({
              id: `recovery-${manualDateKey}`,
              title: recoverySuggestion.title,
              sport: recoverySuggestion.sport,
              subcategory: recoverySuggestion.subcategory,
              notes: recoverySuggestion.notes,
              autoSuggestion: recoverySuggestion,
              durationMin: recoverySuggestion.durationMin,
            });
          }
          const selectedCardId = selectedWorkoutByDay[dayByIndex[day]] ?? workoutCards[0]?.id;
          const selectedCard = workoutCards.find((entry) => entry.id === selectedCardId) ?? workoutCards[0] ?? null;
          const startHref = (() => {
            if (!selectedCard) return `/workouts?day=${day}`;
            if (selectedCard.manualWorkoutId) return `/workouts?day=${day}&manualWorkoutId=${selectedCard.manualWorkoutId}`;
            if (selectedCard.workoutId) return `/workouts?day=${day}&workoutId=${selectedCard.workoutId}`;
            if (selectedCard.autoSuggestion) {
              const autoSuggestion = encodeAutoWorkoutSuggestion(selectedCard.autoSuggestion);
              return `/workouts?day=${day}${autoSuggestion ? `&autoWorkout=${autoSuggestion}` : ""}`;
            }
            return `/workouts?day=${day}`;
          })();
          const editHref = selectedCard?.manualWorkoutId
            ? `/workouts?day=${day}&manual=1&manualWorkoutId=${selectedCard.manualWorkoutId}`
            : `/workouts?day=${day}&manual=1`;

          return (
            <article
              key={day}
              className={`rounded-2xl border p-4 ${day === todayIndex ? "border-green-700 bg-green-950/20" : "border-zinc-800 bg-zinc-900"}`}
            >
              {completedDateSet.has(toLocalDateKey(getDateForWeekday(day))) ? (
                <p className="mb-2 inline-flex rounded-full border border-emerald-500 bg-emerald-500/20 px-2 py-1 text-xs font-semibold text-emerald-200">
                  Workout vollständig erledigt ✅
                </p>
              ) : null}
              <div className="flex items-center justify-between">
                <h3 className="font-semibold">
                  {weekdayNames[day]}{" "}
                  <span className="text-xs text-zinc-400">
                    ({getDateForWeekday(day).toLocaleDateString("de-DE", { day: "2-digit", month: "2-digit" })})
                  </span>
                </h3>

              </div>

              <p className="mt-2 text-lg font-medium">{isRestDisplay ? "Frei / Kein Workout geplant" : suggestedWorkout?.title ?? workout.title}</p>
              {profilePlan ? (
                <p className="mt-2 text-sm text-emerald-300">
                  Profil-Plan: {profilePlan.sessionType} • {profilePlan.intensity} • {profilePlan.minutes} Min
                </p>
              ) : null}
              <div className="mt-3 grid gap-2 md:grid-cols-2">
                {workoutCards.length > 0 && !isRestDisplay ? workoutCards.map((card) => (
                  <button
                    key={card.id}
                    type="button"
                    onClick={() =>
                      setSelectedWorkoutByDay((current) => ({
                        ...current,
                        [dayByIndex[day]]: card.id,
                      }))
                    }
                    className={`rounded-xl border p-3 text-left ${
                      selectedCardId === card.id
                        ? "border-cyan-400 bg-cyan-950/30"
                        : "border-zinc-700 bg-zinc-950/50"
                    }`}
                  >
                    <p className="font-semibold text-zinc-100">{card.title}</p>
                    <p className="text-xs text-zinc-400">{card.sport} • {card.subcategory}</p>
                    <p className="text-xs text-zinc-500">{card.durationMin} Min</p>
                  </button>
                )) : (
                  <p className="rounded-lg border border-zinc-700 bg-zinc-950/40 p-3 text-xs text-zinc-400">
                    {isRestDisplay ? "Tag ist als Frei markiert. Versuche heute trotzdem eine kleine Aktivität 🙌" : "Kein Workout hinterlegt."}
                  </p>
                )}
              </div>
              {selectedCard && !isRestDisplay ? (
                <div className="mt-3 flex flex-wrap gap-2 rounded-lg border border-zinc-700 bg-zinc-950/50 p-2">
                  <Link
                    href={startHref}
                    className="rounded-lg border border-indigo-500 px-3 py-1 text-xs font-semibold text-indigo-300 hover:bg-indigo-950"
                  >
                    {completedDateSet.has(toLocalDateKey(getDateForWeekday(day))) ? "Workout ansehen" : "Workout starten"}
                  </Link>
                  <Link
                    href={editHref}
                    className="rounded-lg border border-amber-500 px-3 py-1 text-xs font-semibold text-amber-300 hover:bg-amber-950"
                  >
                    Workout bearbeiten
                  </Link>
                  <Link
                    href={`/workouts?day=${day}&manual=1`}
                    className="rounded-lg border border-emerald-500 px-3 py-1 text-xs font-semibold text-emerald-300 hover:bg-emerald-950"
                  >
                    Workout hinzufügen
                  </Link>
                  <button
                    type="button"
                    disabled={!selectedCard.manualWorkoutId}
                    onClick={() => {
                      if (!selectedCard.manualWorkoutId) return;
                      deleteManualWorkout(day, selectedCard.manualWorkoutId);
                    }}
                    className="rounded-lg border border-rose-500 px-3 py-1 text-xs font-semibold text-rose-300 hover:bg-rose-950 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    Workout löschen
                  </button>
                  <button
                    type="button"
                    disabled={!selectedCard.manualWorkoutId}
                    onClick={() => {
                      if (!selectedCard.manualWorkoutId) return;
                      moveManualWorkoutToTomorrow(day, selectedCard.manualWorkoutId);
                    }}
                    className="rounded-lg border border-cyan-500 px-3 py-1 text-xs font-semibold text-cyan-300 hover:bg-cyan-950 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    Auf morgen schieben
                  </button>
                  <button
                    type="button"
                    onClick={() => deleteAllManualWorkouts(day)}
                    className="rounded-lg border border-zinc-500 px-3 py-1 text-xs font-semibold text-zinc-200 hover:bg-zinc-800"
                  >
                    Alle löschen
                  </button>
                </div>
              ) : null}
              {!selectedCard || isRestDisplay ? (
                <div className="mt-3">
                  <Link
                    href={`/workouts?day=${day}&manual=1`}
                    className="rounded-lg border border-emerald-500 px-3 py-1 text-xs font-semibold text-emerald-300 hover:bg-emerald-950"
                  >
                    Workout hinzufügen
                  </Link>
                </div>
              ) : null}

              {selectedCard && !isRestDisplay ? (
                <p className="mt-2 text-xs text-zinc-500">{selectedCard.notes}</p>
              ) : isRestDisplay ? (
                <p className="mt-2 text-xs text-emerald-300">Erholung ist Teil vom Plan. Versuche trotzdem jeden Tag eine Kleinigkeit zu schaffen.</p>
              ) : (
                <ul className="mt-3 list-inside list-disc text-sm text-zinc-300">
                  {workout.exercises.map((exercise) => (
                    <li key={`${workout.id}-${exercise.name}`}>{exercise.name}</li>
                  ))}
                </ul>
              )}
            </article>
          );
        })}
      </div>
    </main>
  );
}