"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { type Category, type Exercise, type Workout } from "@/lib/training-data";
import { getWorkoutSessions } from "@/lib/session-storage";
import { loadExercises, loadWorkouts } from "@/lib/training-storage";
import {
  WORKOUT_OVERRIDE_PREFIX,
  WORKOUT_PROGRESS_PREFIX,
  WEEKLY_WORKOUT_PLAN,
  getDateForWeekday,
  getTodayDateKey,
  toLocalDateKey,
} from "@/lib/workout";
import { buildWeeklyPlan, type DayKey, type WeekConfig } from "@/lib/planner";
import {
  buildGeneratedWorkout,
  getFocusProfile,
  pickSubcategoryForDay,
} from "@/lib/player-workout-engine";
import {
  MANUAL_DAY_WORKOUTS_KEY,
  HIDE_ALL_AUTO_WORKOUTS_ID,
  calendarBlocksTrainingForDate,
  readDailyPlanMap,
  readHiddenAutoWorkoutsMap,
  sessionTypeFromPlannedTags,
  storedRegenerationSignals,
  type PlannedWorkoutTag,
  readManualDayDisabledMap,
  writeHiddenAutoWorkoutsMap,
  writeManualDayDisabledMap,
  writeWeeklyRegenSlotMap,
} from "@/lib/activity-calendar";
import { sumExerciseIdsDurationMin } from "@/lib/workout-duration";
import { navigateToWeeklyWorkout, type WeeklyWorkoutNavCard } from "@/lib/weekly-workout-nav";
import { weeklyRecoverySuggestionSlotVisible } from "@/lib/weekly-regeneration";
import WeeklyBasketballCoach from "@/components/WeeklyBasketballCoach";
import PausedWorkoutsBanner from "@/components/PausedWorkoutsBanner";
import TopSubTabs from "@/components/TopSubTabs";
import WeeklyPlanAiButton from "@/components/WeeklyPlanAiButton";
import PageHeader from "@/components/PageHeader";
import { buildBasketballCoachingPriorities } from "@/lib/basketball-coaching";
import { getProgressionState } from "@/lib/level-system";
import { loadTrainingGoalsBundle } from "@/lib/training-goals";
import { findGameStatByDateAndContext, loadGameStats } from "@/lib/game-stats";
import { gamePlanId, type GamePlanContext } from "@/lib/game-plan-ids";
import { addManualGameToWeekday } from "@/lib/plan-day-actions";
import { spieltagCardNotes } from "@/lib/spieltag-defaults";
import { getPlannedSubcategoryFromTags } from "@/lib/planned-subcategory";
import { writeWeeklySuggestionsCache } from "@/lib/weekly-suggestions-cache";
import { getWarmupWorkouts, isWarmupWorkout } from "@/lib/warmup-workouts";
import ShowMoreList from "@/components/ShowMoreList";
import GradientFadeList from "@/components/GradientFadeList";
import WeeklyGamePrepPanel from "@/components/WeeklyGamePrepPanel";
import { PlusIcon } from "@/components/ui/IconButton";

const weekdayOrder = [1, 2, 3, 4, 5, 6, 0] as const;
const weekdayNames: Record<(typeof weekdayOrder)[number], string> = {
  0: "Sonntag",
  1: "Montag",
  2: "Dienstag",
  3: "Mittwoch",
  4: "Donnerstag",
  5: "Freitag",
  6: "Samstag",
};
const REST_QUOTES = [
  "Champions train, but they also recover smart. — LeBron James",
  "Rest at the end, not in the middle. — Kobe Bryant",
  "Small daily improvements are the key to staggering long-term results. — Ray Allen",
  "Success is where preparation and opportunity meet. — Stephen Curry",
];

const dayByIndex: Record<(typeof weekdayOrder)[number], DayKey> = {
  0: "sunday",
  1: "monday",
  2: "tuesday",
  3: "wednesday",
  4: "thursday",
  5: "friday",
  6: "saturday",
};
type ManualDayWorkout = {
  id: string;
  title: string;
  sport: "Basketball" | "Gym" | "Home" | "Regeneration" | "Rest";
  subcategory: string;
  notes: string;
  exerciseIds: string[];
  /** Bei „Auf morgen verschieben“ wird die Original-Dauer übernommen, sodass die Karte die richtige Länge zeigt. */
  durationMin?: number;
};

type ProfileLocalCache = {
  profile: {
    favorite_position: string | null;
  };
  playStyle: string;
  weekConfig: WeekConfig;
  weeklyGoalSessions: number;
  coachWorkoutByDay?: Partial<Record<DayKey, string>>;
};

type PlannedUiEntry = {
  day: DayKey;
  sessionType: string;
  intensity: string;
  minutes: number;
  reason: string;
};

type SuggestedWorkout = {
  workoutId?: string;
  title: string;
  durationMin: number;
  notes: string;
  sport: string;
  subcategory: string;
  exerciseIds?: string[];
  exercises?: string[];
  isAutoGenerated?: boolean;
};

type WorkoutCardItem = {
  id: string;
  title: string;
  sport: string;
  subcategory: string;
  notes: string;
  workoutId?: string;
  autoSuggestion?: SuggestedWorkout;
  manualWorkoutId?: string;
  durationMin: number;
  kind?: "training" | "game" | "game_training";
};

function isGameCard(card: WorkoutCardItem) {
  return card.kind === "game" || card.kind === "game_training" || card.subcategory === "Spiel" || card.subcategory === "Spieltraining";
}

function gameContextForCard(card: WorkoutCardItem): GamePlanContext {
  return card.kind === "game_training" || card.subcategory === "Spieltraining" ? "game_training" : "game";
}

type HiddenAutoWorkoutsMap = Record<string, string[]>;
const SELECTED_WARMUP_BY_DATE_KEY = "bt.selected-warmup-by-date.v1";

function readSelectedWarmupByDate(): Record<string, string> {
  if (typeof window === "undefined") return {};
  const raw = window.localStorage.getItem(SELECTED_WARMUP_BY_DATE_KEY);
  if (!raw) return {};
  try {
    return JSON.parse(raw) as Record<string, string>;
  } catch {
    return {};
  }
}

function writeSelectedWarmupByDate(value: Record<string, string>) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(SELECTED_WARMUP_BY_DATE_KEY, JSON.stringify(value));
}

function buildAutoWorkoutId(dayIndex: (typeof weekdayOrder)[number], sport: string) {
  if (sport === "Regeneration") return `auto-weekly-recovery-${dayIndex}`;
  return `auto-weekly-${dayIndex}`;
}

function getGameCardFromTags(dateKey: string, tags: PlannedWorkoutTag[], fallbackMinutes: number, sessionType?: string): WorkoutCardItem | null {
  if (tags.includes("Spieltag") || sessionType === "game") {
    const prep = findGameStatByDateAndContext(dateKey, "game");
    return {
      id: gamePlanId(dateKey, "game"),
      title: prep?.opponentLabel?.trim() || "Spieltag",
      sport: "Basketball",
      subcategory: "Spiel",
      notes: spieltagCardNotes(prep?.notes),
      durationMin: Math.max(0, fallbackMinutes || 60),
      kind: "game",
    };
  }
  if (tags.includes("Spieltraining") || sessionType === "game-training") {
    const prep = findGameStatByDateAndContext(dateKey, "game_training");
    return {
      id: gamePlanId(dateKey, "game_training"),
      title: prep?.opponentLabel?.trim() || "Spieltraining",
      sport: "Basketball",
      subcategory: "Spieltraining",
      notes: prep?.notes?.trim() || "Tracke Minuten, Intensität, Punkte und Notizen zum Spieltraining.",
      durationMin: Math.max(0, fallbackMinutes || 45),
      kind: "game_training",
    };
  }
  return null;
}

function isEmptyRestCard(card: WorkoutCardItem) {
  return (
    (card.durationMin ?? 0) <= 0 ||
    card.sport === "-" ||
    card.subcategory.toLowerCase() === "frei" ||
    card.title.toLowerCase().includes("freier tag")
  );
}

function isRegenerationCard(card: WorkoutCardItem) {
  return card.sport === "Regeneration" || card.subcategory.toLowerCase().includes("recovery");
}

function isWarmupCard(card: WorkoutCardItem) {
  return isWarmupWorkout({
    id: card.workoutId ?? card.manualWorkoutId ?? card.id,
    name: card.title,
    category: card.sport === "Basketball" ? "Basketball" : "Gym",
    subcategory: card.subcategory,
    level: 1,
    exerciseIds: [],
  });
}

function getCompletionIdsForCard(card: WorkoutCardItem) {
  return [
    card.id,
    card.manualWorkoutId,
    card.workoutId,
    card.autoSuggestion?.workoutId,
  ].filter((id): id is string => Boolean(id));
}

function readWorkoutProgressState() {
  const completed: Record<string, Set<string>> = {};
  const continuable: Record<string, Set<string>> = {};
  if (typeof window === "undefined") return { completed, continuable };

  for (let index = 0; index < window.localStorage.length; index += 1) {
    const key = window.localStorage.key(index);
    if (!key?.startsWith(WORKOUT_PROGRESS_PREFIX)) continue;
    const raw = window.localStorage.getItem(key);
    if (!raw) continue;

    try {
      const parsed = JSON.parse(raw) as {
        date?: string;
        workoutId?: string;
        status?: string;
        elapsedSeconds?: number;
        logs?: Record<string, unknown>;
      };
      if (!parsed.date || !parsed.workoutId) continue;
      const target = parsed.status === "completed" ? completed : continuable;
      if (
        parsed.status === "completed" ||
        parsed.status === "in_progress" ||
        (parsed.elapsedSeconds ?? 0) > 0 ||
        (parsed.logs && Object.values(parsed.logs).some((log) => log && Object.keys(log as Record<string, unknown>).length > 0))
      ) {
        target[parsed.date] = target[parsed.date] ?? new Set<string>();
        target[parsed.date].add(parsed.workoutId);
      }
    } catch {
      // Ignore invalid legacy progress entries.
    }
  }
  return { completed, continuable };
}

function createManualEntryId(): string {
  const random =
    typeof globalThis !== "undefined" && typeof globalThis.crypto?.randomUUID === "function"
      ? globalThis.crypto.randomUUID()
      : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
  return `manual-day-${random}`;
}

function dedupeManualEntries(entries: ManualDayWorkout[]): ManualDayWorkout[] {
  const seen = new Set<string>();
  const out: ManualDayWorkout[] = [];
  for (const entry of entries) {
    if (seen.has(entry.id)) continue;
    seen.add(entry.id);
    out.push(entry);
  }
  return out;
}

function dedupeManualMap(map: Record<string, ManualDayWorkout[]>): Record<string, ManualDayWorkout[]> {
  const out: Record<string, ManualDayWorkout[]> = {};
  let changed = false;
  for (const [key, entries] of Object.entries(map)) {
    const cleaned = dedupeManualEntries(entries);
    if (cleaned.length !== entries.length) changed = true;
    out[key] = cleaned;
  }
  return changed ? out : map;
}

function toNavCard(card: WorkoutCardItem): WeeklyWorkoutNavCard {
  return {
    id: card.id,
    title: card.title,
    sport: card.sport,
    subcategory: card.subcategory,
    notes: card.notes,
    manualWorkoutId: card.manualWorkoutId,
    workoutId: card.workoutId,
    autoSuggestion: card.autoSuggestion
      ? {
          title: card.autoSuggestion.title,
          sport: card.autoSuggestion.sport,
          subcategory: card.autoSuggestion.subcategory,
          notes: card.autoSuggestion.notes,
          exerciseIds: card.autoSuggestion.exerciseIds,
          exercises: card.autoSuggestion.exercises,
          workoutId: card.autoSuggestion.workoutId,
        }
      : undefined,
  };
}

function encodeAutoWorkoutSuggestion(suggestion: SuggestedWorkout) {
  const payload = {
    title: suggestion.title,
    sport: suggestion.sport,
    subcategory: suggestion.subcategory,
    notes: suggestion.notes,
    exerciseIds: suggestion.exerciseIds ?? [],
    exercises: suggestion.exercises ?? [],
  };

  try {
    return encodeURIComponent(JSON.stringify(payload));
  } catch {
    return null;
  }
}

function roundUpToNearestFive(value: number) {
  return Math.ceil(value / 5) * 5;
}

function normalizeExerciseFamily(name: string) {
  return name
    .toLowerCase()
    .replace(/\s*-\s*(rechts|links|right|left)\b/g, "")
    .replace(/\s*[-–]?\s*\d+\s*$/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function buildRelatedExerciseNames(
  workout: Workout,
  exercises: Exercise[],
  exercisesById: Record<string, Exercise>,
) {
  const baseExercises = workout.exerciseIds
    .map((exerciseId) => exercisesById[exerciseId])
    .filter((exercise): exercise is Exercise => Boolean(exercise));
  const familyKeys = new Set(baseExercises.map((exercise) => normalizeExerciseFamily(exercise.name)));
  const related = exercises.filter(
    (exercise) =>
      exercise.category === workout.category &&
      exercise.subcategory === workout.subcategory &&
      familyKeys.has(normalizeExerciseFamily(exercise.name)),
  );
  const mergedNames = [...baseExercises.map((exercise) => exercise.name), ...related.map((exercise) => exercise.name)];
  return [...new Set(mergedNames)];
}

function getSeedIndex(seedSource: string, length: number) {
  if (length <= 0) return 0;
  let hash = 0;
  for (let i = 0; i < seedSource.length; i += 1) {
    hash = (hash * 31 + seedSource.charCodeAt(i)) >>> 0;
  }
  return hash % length;
}

function computeWorkoutDuration(workout: Workout, exercisesById: Record<string, Exercise>) {
  const rawDuration = workout.exerciseIds.reduce((sum, exerciseId) => {
    const exercise = exercisesById[exerciseId];
    return sum + (exercise?.durationMin ?? 10);
  }, 0);

  return roundUpToNearestFive(rawDuration * 1.1);
}

function workoutFitsPlannedSessionType(workout: Workout, sessionType: string): boolean {
  if (sessionType === "gym") return workout.category === "Gym";
  if (sessionType === "basketball") return workout.category === "Basketball";
  if (sessionType === "game-training" || sessionType === "game") return workout.category === "Basketball";
  if (sessionType === "recovery") return workout.category === "Regeneration" || workout.category === "Home";
  if (sessionType === "custom") return true;
  return false;
}

function suggestionFromCatalogWorkout(workout: Workout, exercisesById: Record<string, Exercise>): SuggestedWorkout {
  return {
    workoutId: workout.id,
    title: workout.name,
    durationMin: computeWorkoutDuration(workout, exercisesById),
    notes: "Vorschlag vom KI-Wochenplan (manuell änderbar).",
    sport: workout.category,
    subcategory: workout.subcategory,
    exerciseIds: workout.exerciseIds,
    exercises: (workout.exerciseIds ?? [])
      .map((id) => exercisesById[id]?.name)
      .filter((name): name is string => Boolean(name)),
  };
}

function buildFallbackSuggestion(mode: string, minutes: number): SuggestedWorkout | null {
  if (mode === "none" || mode === "recovery" || minutes <= 0) {
    return {
      title: "Freier Tag",
      durationMin: 0,
      notes: "Heute ist ein freier Tag. Versuche trotzdem eine kleine aktive Gewohnheit zu schaffen 💪",
      sport: "-",
      subcategory: "Frei",
    };
  }

  return null;
}

function buildRecoverySuggestion(day: DayKey, exercises: Exercise[]): SuggestedWorkout {
  const generated = buildGeneratedWorkout({
    day,
    category: "Regeneration",
    subcategory: "Mobilität & Dehnung",
    targetMinutes: 15,
    exercisePool: exercises,
  });
  return {
    title: generated.name,
    durationMin: generated.durationMin,
    notes: `Kurz-Recovery: ${generated.notes}`,
    sport: generated.category,
    subcategory: generated.subcategory,
    exerciseIds: generated.exerciseIds,
    exercises: generated.exerciseNames,
    isAutoGenerated: true,
  };
}

function syncNoTimeForDate(dateKey: string) {
  const dailyRaw = window.localStorage.getItem("bt.daily-plan.v1");
  const dailyPlan = dailyRaw ? (JSON.parse(dailyRaw) as Record<string, PlannedWorkoutTag[]>) : {};
  dailyPlan[dateKey] = [];
  window.localStorage.setItem("bt.daily-plan.v1", JSON.stringify(dailyPlan));

  const parsedDate = new Date(`${dateKey}T00:00:00`);
  const dayMap: Record<number, DayKey> = {
    0: "sunday",
    1: "monday",
    2: "tuesday",
    3: "wednesday",
    4: "thursday",
    5: "friday",
    6: "saturday",
  };
  const targetDay = dayMap[parsedDate.getDay()];
  const rawProfile = window.localStorage.getItem("profile_cache_v4");
  if (!rawProfile) return;
  try {
    const parsed = JSON.parse(rawProfile) as { weekConfig?: Partial<Record<DayKey, { mode: string; minutes: number }>> };
        parsed.weekConfig = {
      ...(parsed.weekConfig ?? {}),
      [targetDay]: { mode: "unavailable", minutes: 0 },
    };
    window.localStorage.setItem("profile_cache_v4", JSON.stringify(parsed));
  } catch {
    // noop
  }
}

function isTodayOrFutureDate(dateKey: string) {
  const todayKey = toLocalDateKey(new Date());
  return dateKey >= todayKey;
}

function selectBestWorkout(
  mode: string,
  day: DayKey,
  targetMinutes: number,
  workouts: Workout[],
  exercises: Exercise[],
  exercisesById: Record<string, Exercise>,
  freshnessMapByCategory: Record<Category, Record<string, number>>,
  usedWorkoutIds: Set<string>,
  weeklySubcategoryUsage: Record<Category, Record<string, number>>,
  avoidSubcategories: Partial<Record<Category, string[]>>,
  position: string,
  playStyle: string,
  lastAssignedSubcategoryByCategory: Partial<Record<Category, string>>,
  basketballCoachingPriorities: string[] = [],
  plannedSubcategoryOverride?: string | null,
): SuggestedWorkout {
  const isGameMode = mode === "game" || mode === "game-training" || mode === "game_day" || mode === "game_training";
  const targetWithExtra = isGameMode ? (mode === "game" || mode === "game_day" ? 20 : 15) : targetMinutes;
  const modeLabel = isGameMode ? (mode === "game" || mode === "game_day" ? "Spieltag Warm-Up" : "Spieltraining Warm-Up") : "Direktes Training";
  if (mode === "recovery") {
    return buildRecoverySuggestion(day, exercises);
  }
  const fallback = buildFallbackSuggestion(mode, targetWithExtra);
  if (fallback) return fallback;

  const desiredCategory: Category =
    mode === "gym" ? "Gym" : "Basketball";
  let focusProfile = getFocusProfile({ position, playStyle });
  if (desiredCategory === "Basketball" && basketballCoachingPriorities.length > 0) {
    focusProfile = {
      ...focusProfile,
      basketball: [...new Set([...basketballCoachingPriorities, ...focusProfile.basketball])],
    };
  }

  const categoryFreshness = freshnessMapByCategory[desiredCategory] ?? {};
  const subcategoryRank = (subcategory: string) => categoryFreshness[subcategory] ?? 0;
  const weeklyUsage = weeklySubcategoryUsage[desiredCategory] ?? {};
  const subcategoryWeeklyCount = (subcategory: string) => weeklyUsage[subcategory] ?? 0;

  const filteredByCategory = workouts.filter((workout) => workout.category === desiredCategory);
  const availableSubcategories = [
    ...new Set(
      filteredByCategory.map((workout) => workout.subcategory),
    ),
  ];
  const fromPlan =
    plannedSubcategoryOverride &&
    availableSubcategories.some((sub) => sub.toLowerCase() === plannedSubcategoryOverride.toLowerCase())
      ? plannedSubcategoryOverride
      : null;
  const preferredSubcategory = isGameMode
    ? "Warm-Up"
    : fromPlan ??
      pickSubcategoryForDay({
        category: desiredCategory,
        focusProfile,
        usage: weeklySubcategoryUsage[desiredCategory] ?? {},
        availableSubcategories,
      });
  if (filteredByCategory.length === 0) {
    const generated = buildGeneratedWorkout({
      day,
      category: desiredCategory,
      subcategory: desiredCategory,
      targetMinutes: roundUpToNearestFive(targetWithExtra),
      exercisePool: exercises,
    });
    return {
      title: generated.name,
      durationMin: generated.durationMin,
      notes: generated.notes,
      sport: generated.category,
      subcategory: generated.subcategory,
      exerciseIds: generated.exerciseIds,
      exercises: generated.exerciseNames,
      isAutoGenerated: true,
    };
  }

  const filtered = filteredByCategory
    .map((workout) => ({
      workout,
      duration: computeWorkoutDuration(workout, exercisesById),
    }))
    .sort((left, right) => {
      if (left.workout.subcategory === preferredSubcategory && right.workout.subcategory !== preferredSubcategory) {
        return -1;
      }
      if (right.workout.subcategory === preferredSubcategory && left.workout.subcategory !== preferredSubcategory) {
        return 1;
      }
      return 0;
    });
  const unusedPool = filtered.filter((entry) => !usedWorkoutIds.has(entry.workout.id));
  const avoidForCategory = avoidSubcategories[desiredCategory] ?? [];
  const withoutAvoidedSubcategories = unusedPool.filter(
    (entry) => !avoidForCategory.includes(entry.workout.subcategory),
  );
  const pool =
    withoutAvoidedSubcategories.length > 0
      ? withoutAvoidedSubcategories
      : unusedPool.length > 0
        ? unusedPool
        : [];
  const nonConsecutivePool = pool.filter(
    (entry) => entry.workout.subcategory !== lastAssignedSubcategoryByCategory[desiredCategory],
  );
  const dayPool = nonConsecutivePool.length > 0 ? nonConsecutivePool : pool;

  if (dayPool.length === 0) {
    const generated = buildGeneratedWorkout({
      day,
      category: desiredCategory,
      subcategory: preferredSubcategory,
      targetMinutes: targetWithExtra,
      exercisePool: exercises,
    });
    weeklySubcategoryUsage[desiredCategory] = {
      ...weeklySubcategoryUsage[desiredCategory],
      [generated.subcategory]:
        (weeklySubcategoryUsage[desiredCategory]?.[generated.subcategory] ?? 0) + 1,
    };
    return {
      title: generated.name,
      durationMin: generated.durationMin,
      notes: `${modeLabel}: ${generated.notes} (keine duplizierten Workouts in dieser Woche).`,
      sport: generated.category,
      subcategory: generated.subcategory,
      exerciseIds: generated.exerciseIds,
      exercises: generated.exerciseNames,
      isAutoGenerated: true,
    };
  }

  const compliantPool = dayPool.filter(
    (entry) =>
      (weeklySubcategoryUsage[desiredCategory]?.[entry.workout.subcategory] ?? 0) <
      (desiredCategory === "Gym" ? 2 : 2),
  );
  const effectivePool = compliantPool.length > 0 ? compliantPool : dayPool;

  const sortedPool = [...effectivePool].sort((a, b) => {
    const weeklyDiff = subcategoryWeeklyCount(a.workout.subcategory) - subcategoryWeeklyCount(b.workout.subcategory);
    if (weeklyDiff !== 0) return weeklyDiff;

    const freshnessDiff = subcategoryRank(a.workout.subcategory) - subcategoryRank(b.workout.subcategory);
    if (freshnessDiff !== 0) return freshnessDiff;

    const durationDiff = Math.abs(a.duration - targetWithExtra) - Math.abs(b.duration - targetWithExtra);
    if (durationDiff !== 0) return durationDiff;

    const aSeed = getSeedIndex(`${day}-${a.workout.id}`, 97);
    const bSeed = getSeedIndex(`${day}-${b.workout.id}`, 97);
    return aSeed - bSeed;
  });
  const best = sortedPool[0];

  const shouldGenerateWorkout =
    best.workout.subcategory !== preferredSubcategory &&
    (weeklySubcategoryUsage[desiredCategory]?.[preferredSubcategory] ?? 0) <
      (desiredCategory === "Gym" ? 2 : 2);

  if (shouldGenerateWorkout) {
    const generated = buildGeneratedWorkout({
      day,
      category: desiredCategory,
      subcategory: preferredSubcategory,
      targetMinutes: targetWithExtra,
      exercisePool: exercises,
    });
    weeklySubcategoryUsage[desiredCategory] = {
      ...weeklySubcategoryUsage[desiredCategory],
      [generated.subcategory]:
        (weeklySubcategoryUsage[desiredCategory]?.[generated.subcategory] ?? 0) + 1,
    };
    return {
      title: generated.name,
      durationMin: generated.durationMin,
      notes: `${modeLabel}: ${generated.notes} Fokus via Spielertyp-Mapping.`,
      sport: generated.category,
      subcategory: generated.subcategory,
      exerciseIds: generated.exerciseIds,
      exercises: generated.exerciseNames,
      isAutoGenerated: true,
    };
  }

  usedWorkoutIds.add(best.workout.id);
  weeklySubcategoryUsage[desiredCategory] = {
    ...weeklySubcategoryUsage[desiredCategory],
    [best.workout.subcategory]: subcategoryWeeklyCount(best.workout.subcategory) + 1,
  };

  return {
    workoutId: best.workout.id,
    title: best.workout.name,
    durationMin: best.duration,
    notes: `${modeLabel}: Match zu ${targetWithExtra} Min (${best.workout.category} • ${best.workout.subcategory})`,
    sport: best.workout.category,
    subcategory: best.workout.subcategory,
    exerciseIds: best.workout.exerciseIds,
    exercises: buildRelatedExerciseNames(best.workout, exercises, exercisesById),
  };
}

export default function WeeklyWorkoutPage() {
  const router = useRouter();
  const [todayIndex, setTodayIndex] = useState<(typeof weekdayOrder)[number] | null>(null);

  useEffect(() => {
    setTodayIndex(new Date().getDay() as (typeof weekdayOrder)[number]);
  }, []);

  const orderedDays = useMemo(
    () =>
      todayIndex === null
        ? [...weekdayOrder]
        : [...weekdayOrder].sort(
            (left, right) => ((left - todayIndex + 7) % 7) - ((right - todayIndex + 7) % 7),
          ),
    [todayIndex],
  );
  const [plannedEntries, setPlannedEntries] = useState<PlannedUiEntry[] | null>(null);
  const [suggestionsByDay, setSuggestionsByDay] = useState<Record<DayKey, SuggestedWorkout> | null>(null);
  /** Auto-Plan unabhängig von manuellen Einträgen (zeigt echtes Engine-Ergebnis). */
  const [autoSuggestionsByDay, setAutoSuggestionsByDay] = useState<Record<DayKey, SuggestedWorkout> | null>(null);
  const [manualWorkoutsByDate, setManualWorkoutsByDate] = useState<Record<string, ManualDayWorkout[]>>({});
  const [selectedWorkoutByDay, setSelectedWorkoutByDay] = useState<Partial<Record<DayKey, string>>>({});
  const [selectedWarmupByDate, setSelectedWarmupByDate] = useState<Record<string, string>>({});
  const [manualVersion, setManualVersion] = useState(0);
  const [disabledManualDays, setDisabledManualDays] = useState<Record<string, boolean>>({});
  const [hiddenAutoWorkoutsByDate, setHiddenAutoWorkoutsByDate] = useState<HiddenAutoWorkoutsMap>({});
  const [dailyPlanByDate, setDailyPlanByDate] = useState<Record<string, PlannedWorkoutTag[]>>({});
  const [warmupCatalogWorkouts, setWarmupCatalogWorkouts] = useState<Workout[]>([]);
  const [profileVersion, setProfileVersion] = useState(0);
  /** Nur nach Mount gesetzt — vermeidet Hydration-Mismatch (localStorage vs. SSR-Default). */
  const [mesocycleLabel, setMesocycleLabel] = useState<string | null>(null);
  const [workoutSessions, setWorkoutSessions] = useState<ReturnType<typeof getWorkoutSessions>>([]);
  const [completedProgressIdsByDate, setCompletedProgressIdsByDate] = useState<Record<string, Set<string>>>({});
  const [continuableProgressIdsByDate, setContinuableProgressIdsByDate] = useState<Record<string, Set<string>>>({});
  const availableExercises = useMemo(() => loadExercises(), []);
  const exercisesById = useMemo(
    () => Object.fromEntries(availableExercises.map((exercise) => [exercise.id, exercise])),
    [availableExercises],
  );
  const completedDateSet = new Set(workoutSessions.map((session) => toLocalDateKey(new Date(session.dateISO))));
  const completedWorkoutIdsByDate = workoutSessions.reduce<Record<string, Set<string>>>((acc, session) => {
    const key = toLocalDateKey(new Date(session.dateISO));
    const current = acc[key] ?? new Set<string>();
    current.add(session.workoutId);
    acc[key] = current;
    return acc;
  }, {});

  useEffect(() => {
    if (todayIndex === null) return;

    const timer = window.setTimeout(() => {
      const raw = window.localStorage.getItem("profile_cache_v4");
      if (!raw) return;

      try {
        const parsed = JSON.parse(raw) as ProfileLocalCache;
        const mesocyclePhase = loadTrainingGoalsBundle().mesocyclePhase;
        const computed = buildWeeklyPlan({
          position: parsed.profile.favorite_position ?? "sg",
          playStyle: parsed.playStyle,
          weekConfig: parsed.weekConfig,
          weeklyGoalSessions: parsed.weeklyGoalSessions,
          mesocyclePhase,
        });

        setPlannedEntries(computed);

        const exercises = loadExercises();
        const workouts = loadWorkouts();
        setWarmupCatalogWorkouts(getWarmupWorkouts(workouts));
        const exercisesById = Object.fromEntries(exercises.map((exercise) => [exercise.id, exercise]));
        const sessions = getWorkoutSessions();
        const workoutLookup = new Map(workouts.map((workout) => [workout.id, workout]));
        const freshnessMapByCategory = sessions.reduce(
          (accumulator, session, index) => {
            const workout = workoutLookup.get(session.workoutId);
            const category = (workout?.category ?? session.workoutCategory) as Category | undefined;
            const subcategory = workout?.subcategory ?? session.workoutSubcategory;
            if (!category || !subcategory) return accumulator;
            const next = accumulator[category] ?? {};
            if (next[subcategory] === undefined) {
                            next[subcategory] = index + 1;
            }
            accumulator[category] = next;
            return accumulator;
          },
          {} as Record<Category, Record<string, number>>,
        );
        const usedWorkoutIds = new Set<string>();
        const weeklySubcategoryUsage: Record<Category, Record<string, number>> = {
          Basketball: {},
          Gym: {},
          Home: {},
          Regeneration: {},
        };
        const lastAssignedSubcategoryByCategory: Partial<Record<Category, string>> = {};
        const rawManual = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
        const rawManualByDate = rawManual ? (JSON.parse(rawManual) as Record<string, ManualDayWorkout[]>) : {};
        const manualByDate = dedupeManualMap(rawManualByDate);
        if (manualByDate !== rawManualByDate) {
          window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(manualByDate));
        }
        const disabledMap = readManualDayDisabledMap();
        const hiddenAutoMap = readHiddenAutoWorkoutsMap();
        const dailyPlanAtBuild = readDailyPlanMap();
        setDailyPlanByDate(dailyPlanAtBuild);
        setSelectedWarmupByDate(readSelectedWarmupByDate());
        setManualWorkoutsByDate(manualByDate);
        setDisabledManualDays(disabledMap);
        setHiddenAutoWorkoutsByDate(hiddenAutoMap);
        const manualByDay: Partial<Record<DayKey, ManualDayWorkout[]>> = {};
        weekdayOrder.forEach((index) => {
          const date = toLocalDateKey(getDateForWeekday(index));
          const dayKey = dayByIndex[index];
          const entries = manualByDate[date] ?? [];
          if (!entries.length) return;
          manualByDay[dayKey] = entries;
          entries.forEach((entry) => {
            const cat = entry.sport as Category;
            weeklySubcategoryUsage[cat] = {
              ...weeklySubcategoryUsage[cat],
              [entry.subcategory]: (weeklySubcategoryUsage[cat]?.[entry.subcategory] ?? 0) + 1,
            };
            lastAssignedSubcategoryByCategory[cat] = entry.subcategory;
          });
        });
        const dateKey = getTodayDateKey();
        const overrideWorkoutId = window.localStorage.getItem(`${WORKOUT_OVERRIDE_PREFIX}${dateKey}`);
        const overrideWorkout = overrideWorkoutId
          ? workouts.find((workout) => workout.id === overrideWorkoutId)
          : undefined;
        const avoidSubcategories: Partial<Record<Category, string[]>> = {};
        if (overrideWorkout) {
          usedWorkoutIds.add(overrideWorkout.id);
          avoidSubcategories[overrideWorkout.category] = [overrideWorkout.subcategory];
        }
        const coachingPriorities = buildBasketballCoachingPriorities(
          sessions,
          parsed.profile.favorite_position ?? "sg",
          parsed.playStyle,
          getProgressionState().level,
        );

        const coachByDay = parsed.coachWorkoutByDay;

        const suggested = {} as Record<DayKey, SuggestedWorkout>;
        const autoSuggested = {} as Record<DayKey, SuggestedWorkout>;
        computed.forEach((entry) => {
          const dayIndex = weekdayOrder.find((idx) => dayByIndex[idx] === entry.day) ?? 1;
          const planDateKey = toLocalDateKey(getDateForWeekday(dayIndex));
          const dayTags = dailyPlanAtBuild[planDateKey];
          if (dayTags !== undefined && dayTags.length === 0) {
            const freeDay: SuggestedWorkout = {
              title: "Frei · Keine Zeit",
              durationMin: 0,
              notes: "",
              sport: "-",
              subcategory: "-",
            };
            autoSuggested[entry.day] = freeDay;
            suggested[entry.day] = freeDay;
            return;
          }
          const tagSessionType = dayTags?.length ? sessionTypeFromPlannedTags(dayTags) : null;
          const effectiveEntry =
            tagSessionType && tagSessionType !== "none"
              ? { ...entry, sessionType: tagSessionType }
              : entry;
          const plannedBasketballSub =
            dayTags?.length && effectiveEntry.sessionType === "basketball"
              ? getPlannedSubcategoryFromTags(dayTags, "Basketball")
              : null;
          const plannedGymSub =
            dayTags?.length && effectiveEntry.sessionType === "gym"
              ? getPlannedSubcategoryFromTags(dayTags, "Gym")
              : null;
          const autoPick = selectBestWorkout(
            effectiveEntry.sessionType,
            effectiveEntry.day,
            effectiveEntry.minutes,
            workouts,
            exercises,
            exercisesById,
            freshnessMapByCategory,
            usedWorkoutIds,
            weeklySubcategoryUsage,
            avoidSubcategories,
            parsed.profile.favorite_position ?? "sg",
            parsed.playStyle,
            lastAssignedSubcategoryByCategory,
            coachingPriorities,
            plannedBasketballSub ?? plannedGymSub,
          );

          autoSuggested[entry.day] = autoPick;

          const manualFirst = manualByDay[entry.day]?.[0];
          const manualFirstDuration = manualFirst
            ? manualFirst.durationMin
              ?? (manualFirst.exerciseIds?.length
                ? sumExerciseIdsDurationMin(manualFirst.exerciseIds, exercisesById)
                : entry.minutes)
            : entry.minutes;

          const coachId = coachByDay?.[entry.day];
          const coachWorkout = coachId ? workouts.find((w) => w.id === coachId) : undefined;
          const coachSuggestion =
            !manualFirst && coachWorkout && workoutFitsPlannedSessionType(coachWorkout, effectiveEntry.sessionType)
              ? suggestionFromCatalogWorkout(coachWorkout, exercisesById)
              : null;

          suggested[entry.day] = manualFirst
            ? {
                title: manualFirst.title ?? "Manuelles Workout",
                durationMin: manualFirstDuration,
                notes: manualFirst.notes || "Manuell geplant.",
                sport: manualFirst.sport ?? "Basketball",
                subcategory: manualFirst.subcategory ?? "-",
                exerciseIds: manualFirst.exerciseIds ?? [],
                exercises: (manualFirst.exerciseIds ?? [])
                  .map((exerciseId) => exercisesById[exerciseId]?.name)
                  .filter((name): name is string => Boolean(name)),
              }
            : coachSuggestion ?? autoPick;

          const usageSource = suggested[entry.day];
          const category = usageSource.sport as Category | undefined;
          if (!category || (category !== "Basketball" && category !== "Gym" && category !== "Home")) return;
          lastAssignedSubcategoryByCategory[category] = usageSource.subcategory;
        });

        if (overrideWorkout) {
          const todayKey = dayByIndex[todayIndex];
          const overrideSuggestion = {
            workoutId: overrideWorkout.id,
            title: overrideWorkout.name,
            durationMin: computeWorkoutDuration(overrideWorkout, exercisesById),
            notes: "Manuell für heute gewählt.",
            sport: overrideWorkout.category,
            subcategory: overrideWorkout.subcategory,
          };
          suggested[todayKey] = overrideSuggestion;
          autoSuggested[todayKey] = overrideSuggestion;
        }

        setSuggestionsByDay(suggested);
        setAutoSuggestionsByDay(autoSuggested);
        writeWeeklySuggestionsCache(suggested, autoSuggested);
        window.dispatchEvent(new Event("bt:weekly-suggestions-updated"));
      } catch {
        setPlannedEntries(null);
        setSuggestionsByDay(null);
        setAutoSuggestionsByDay(null);
        setManualWorkoutsByDate({});
      }
    }, 0);

    return () => window.clearTimeout(timer);
  }, [todayIndex, manualVersion, profileVersion]);

  useEffect(() => {
    const refreshProgressState = () => {
      const nextProgressState = readWorkoutProgressState();
      setCompletedProgressIdsByDate(nextProgressState.completed);
      setContinuableProgressIdsByDate(nextProgressState.continuable);
    };
    const refreshProfilePlan = () => {
      setWorkoutSessions(getWorkoutSessions());
      refreshProgressState();
      setDailyPlanByDate(readDailyPlanMap());
      setWarmupCatalogWorkouts(getWarmupWorkouts(loadWorkouts()));
      setProfileVersion((current) => current + 1);
    };
    const refreshCompletionState = () => {
      setWorkoutSessions(getWorkoutSessions());
      refreshProgressState();
      setManualVersion((current) => current + 1);
    };
    refreshProfilePlan();
    window.addEventListener("storage", refreshProfilePlan);
    window.addEventListener("focus", refreshProfilePlan);
    window.addEventListener("bt:plan-updated", refreshProfilePlan);
    window.addEventListener("bt:game-stats-updated", refreshProfilePlan);
    window.addEventListener("bt:sessions-updated", refreshCompletionState);
    window.addEventListener("bt:workout-progress-updated", refreshCompletionState);
    return () => {
      window.removeEventListener("storage", refreshProfilePlan);
      window.removeEventListener("focus", refreshProfilePlan);
      window.removeEventListener("bt:plan-updated", refreshProfilePlan);
      window.removeEventListener("bt:game-stats-updated", refreshProfilePlan);
      window.removeEventListener("bt:sessions-updated", refreshCompletionState);
      window.removeEventListener("bt:workout-progress-updated", refreshCompletionState);
    };
  }, []);

  useEffect(() => {
    const labels: Record<string, string> = {
      base: "Basis",
      build: "Aufbau",
      peak: "Peak",
      deload: "Deload",
    };
    const syncMesocycle = () => {
      const phase = loadTrainingGoalsBundle().mesocyclePhase ?? "build";
      setMesocycleLabel(labels[phase] ?? phase);
    };
    syncMesocycle();
    window.addEventListener("bt:training-goals-updated", syncMesocycle);
    return () => window.removeEventListener("bt:training-goals-updated", syncMesocycle);
  }, []);

  const regenSlotByDateKey = useMemo(() => {
    if (!suggestionsByDay || !autoSuggestionsByDay) return {};
    const out: Record<string, boolean> = {};
    for (const day of weekdayOrder) {
      const manualDateKey = toLocalDateKey(getDateForWeekday(day));
      const dayManualEntries = manualWorkoutsByDate[manualDateKey] ?? [];
      const hiddenCardIds = new Set(hiddenAutoWorkoutsByDate[manualDateKey] ?? []);
      const isDayDisabled = disabledManualDays[manualDateKey] === true;
      const headlineSuggested = suggestionsByDay[dayByIndex[day]] ?? null;
      const autoSuggestedWorkout = autoSuggestionsByDay[dayByIndex[day]] ?? null;
      out[manualDateKey] = weeklyRecoverySuggestionSlotVisible({
        manualDateKey,
        dayManualEntries,
        isDayDisabled,
        headlineSuggestedWorkout: headlineSuggested,
        autoSuggestedWorkout,
        hiddenCardIds,
      });
    }
    return out;
  }, [autoSuggestionsByDay, disabledManualDays, hiddenAutoWorkoutsByDate, manualWorkoutsByDate, suggestionsByDay]);

  useEffect(() => {
    if (!suggestionsByDay || !autoSuggestionsByDay) return;
    writeWeeklyRegenSlotMap(regenSlotByDateKey);
  }, [autoSuggestionsByDay, regenSlotByDateKey, suggestionsByDay]);

  const deleteManualWorkout = (dayIndex: (typeof weekdayOrder)[number], manualWorkoutId: string) => {
    const dateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const raw = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw) as Record<string, ManualDayWorkout[]>;
      const nextEntries = (parsed[dateKey] ?? []).filter((entry) => entry.id !== manualWorkoutId);
      const next = { ...parsed, [dateKey]: nextEntries };
      if (nextEntries.length === 0) {
        delete next[dateKey];
        const disabledMap = { ...readManualDayDisabledMap() };
        delete disabledMap[dateKey];
        writeManualDayDisabledMap(disabledMap);
        setDisabledManualDays(disabledMap);
      }
      window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(next));
      window.dispatchEvent(new Event("bt:plan-updated"));
      setManualWorkoutsByDate(next);
      setManualVersion((current) => current + 1);
    } catch {
      // noop
    }
  };
  const moveManualWorkoutToTomorrow = (dayIndex: (typeof weekdayOrder)[number], manualWorkoutId: string) => {
    const sourceDateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const sourceDate = new Date(`${sourceDateKey}T00:00:00`);
    sourceDate.setDate(sourceDate.getDate() + 1);
    const targetDateKey = toLocalDateKey(sourceDate);
    const raw = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw) as Record<string, ManualDayWorkout[]>;
      const currentEntries = parsed[sourceDateKey] ?? [];
      const moving = currentEntries.find((entry) => entry.id === manualWorkoutId);
      if (!moving) return;

      parsed[sourceDateKey] = currentEntries.filter((entry) => entry.id !== manualWorkoutId);
      if (parsed[sourceDateKey].length === 0) {
        delete parsed[sourceDateKey];
        const disabledMap = { ...readManualDayDisabledMap() };
        delete disabledMap[sourceDateKey];
        writeManualDayDisabledMap(disabledMap);
        setDisabledManualDays(disabledMap);
      }

      const existingTargetEntries = parsed[targetDateKey] ?? [];
      const targetHasSameId = existingTargetEntries.some((entry) => entry.id === moving.id);
      const movedEntry: ManualDayWorkout = targetHasSameId
        ? { ...moving, id: createManualEntryId() }
        : { ...moving };
      // Original-Dauer auf der Karte beibehalten – nicht an Ziel-Tag anpassen.
      if (movedEntry.durationMin == null && Array.isArray(movedEntry.exerciseIds) && movedEntry.exerciseIds.length > 0) {
        const exercisesById = Object.fromEntries(availableExercises.map((exercise) => [exercise.id, exercise]));
        const computed = sumExerciseIdsDurationMin(movedEntry.exerciseIds, exercisesById);
        if (computed > 0) movedEntry.durationMin = computed;
      }
      parsed[targetDateKey] = dedupeManualEntries([movedEntry, ...existingTargetEntries]);

      const disabledMap = readManualDayDisabledMap();
      if (disabledMap[targetDateKey]) {
        const nextDisabled = { ...disabledMap };
        delete nextDisabled[targetDateKey];
        writeManualDayDisabledMap(nextDisabled);
        setDisabledManualDays(nextDisabled);
      }
      window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
      window.dispatchEvent(new Event("bt:plan-updated"));
      setManualWorkoutsByDate(parsed);
      setManualVersion((current) => current + 1);
    } catch {
      // noop
    }
  };

  const moveAutoWorkoutToTomorrow = (dayIndex: (typeof weekdayOrder)[number], selectedCard: WorkoutCardItem) => {
    if (isEmptyRestCard(selectedCard)) return;
    const sourceDateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const sourceDate = new Date(`${sourceDateKey}T00:00:00`);
    sourceDate.setDate(sourceDate.getDate() + 1);
    const targetDateKey = toLocalDateKey(sourceDate);
    const raw = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    const parsed = raw ? (JSON.parse(raw) as Record<string, ManualDayWorkout[]>) : {};

    const isRecoveryCard = selectedCard.id.startsWith("recovery-") || selectedCard.sport === "Regeneration";
    const autoTitle = selectedCard.title.replace(/\s*\(.+\)\s*$/, "").trim();
    const targetEntries = parsed[targetDateKey] ?? [];

    const alreadyOnTarget = targetEntries.some(
      (entry) =>
        entry.title === autoTitle &&
        entry.sport === ((selectedCard.sport as ManualDayWorkout["sport"]) ?? "Basketball") &&
        entry.subcategory === selectedCard.subcategory,
    );

    if (!alreadyOnTarget) {
      const originalDuration = selectedCard.durationMin
        ?? selectedCard.autoSuggestion?.durationMin
        ?? null;
      const autoEntry: ManualDayWorkout = {
        id: createManualEntryId(),
        title: autoTitle,
        sport: (selectedCard.sport as ManualDayWorkout["sport"]) ?? "Basketball",
        subcategory: selectedCard.subcategory,
        notes: selectedCard.notes || "Aus Auto-Plan verschoben.",
        exerciseIds: selectedCard.autoSuggestion?.exerciseIds ?? [],
        durationMin: originalDuration ?? undefined,
      };
      parsed[targetDateKey] = dedupeManualEntries([autoEntry, ...targetEntries]);
    }

    window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
    window.dispatchEvent(new Event("bt:plan-updated"));

    // Karte vom Quell-Tag immer verstecken (auch Recovery), damit sie verschwindet.
    hideAutoWorkoutCard(dayIndex, selectedCard.id);

    if (!isRecoveryCard) {
      const sourceRecoveryCardId = `recovery-${sourceDateKey}`;
      const sourceHiddenMap = readHiddenAutoWorkoutsMap();
      const nextHiddenSource = { ...sourceHiddenMap };
      nextHiddenSource[sourceDateKey] = [
        ...new Set([...(nextHiddenSource[sourceDateKey] ?? []), sourceRecoveryCardId]),
      ];
      writeHiddenAutoWorkoutsMap(nextHiddenSource);
      setHiddenAutoWorkoutsByDate(nextHiddenSource);

      const targetHasRecovery = (parsed[targetDateKey] ?? []).some(
        (entry) => entry.sport === "Regeneration",
      );
      if (!targetHasRecovery) {
        const targetRecovery = buildRecoverySuggestion(dayByIndex[dayIndex], availableExercises);
        const recoveryEntry: ManualDayWorkout = {
          id: createManualEntryId(),
          title: targetRecovery.title,
          sport: "Regeneration",
          subcategory: targetRecovery.subcategory,
          notes: targetRecovery.notes,
          exerciseIds: targetRecovery.exerciseIds ?? [],
          durationMin: targetRecovery.durationMin,
        };
        parsed[targetDateKey] = dedupeManualEntries([...(parsed[targetDateKey] ?? []), recoveryEntry]);
        window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
      }
    }

    const disabledMap = readManualDayDisabledMap();
    if (disabledMap[targetDateKey]) {
      const nextDisabled = { ...disabledMap };
      delete nextDisabled[targetDateKey];
      writeManualDayDisabledMap(nextDisabled);
      setDisabledManualDays(nextDisabled);
    }

    setManualWorkoutsByDate(parsed);
    setManualVersion((current) => current + 1);
  };

  const disableDayAsNoTime = (dayIndex: (typeof weekdayOrder)[number]) => {
    const dateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const rawManual = window.localStorage.getItem(MANUAL_DAY_WORKOUTS_KEY);
    if (rawManual) {
      try {
        const parsed = JSON.parse(rawManual) as Record<string, ManualDayWorkout[]>;
        delete parsed[dateKey];
        window.localStorage.setItem(MANUAL_DAY_WORKOUTS_KEY, JSON.stringify(parsed));
        window.dispatchEvent(new Event("bt:plan-updated"));
        setManualWorkoutsByDate(parsed);
      } catch {
        // noop
      }
    }
    const hiddenMap = readHiddenAutoWorkoutsMap();
    if (hiddenMap[dateKey]) {
      const nextHidden = { ...hiddenMap };
      delete nextHidden[dateKey];
      writeHiddenAutoWorkoutsMap(nextHidden);
      setHiddenAutoWorkoutsByDate(nextHidden);
    }
    const disabledMap = { ...readManualDayDisabledMap(), [dateKey]: true };
    writeManualDayDisabledMap(disabledMap);
    setDisabledManualDays(disabledMap);
    const hasCompleted = completedDateSet.has(dateKey);
    if (isTodayOrFutureDate(dateKey) && !hasCompleted) {
      syncNoTimeForDate(dateKey);
    }
    setManualVersion((current) => current + 1);
  };

  const hideAutoWorkoutCard = (dayIndex: (typeof weekdayOrder)[number], cardId: string) => {
    const dateKey = toLocalDateKey(getDateForWeekday(dayIndex));
    const currentMap = readHiddenAutoWorkoutsMap();
    const hiddenForDate = new Set(currentMap[dateKey] ?? []);
    hiddenForDate.add(cardId);
    const nextMap = { ...currentMap, [dateKey]: Array.from(hiddenForDate) };
    writeHiddenAutoWorkoutsMap(nextMap);
    setHiddenAutoWorkoutsByDate(nextMap);
    const isRecoveryCard = cardId.startsWith("recovery-");
    const hasCompleted = completedDateSet.has(dateKey);
    const isSingleOnlyCard = cardId.startsWith("game-") || warmupCatalogWorkouts.some((workout) => workout.id === cardId);
    const dayKey = dayByIndex[dayIndex];
    const isGameDay =
      (dailyPlanByDate[dateKey] ?? []).some((tag) => tag === "Spieltag" || tag === "Spieltraining") ||
      plannedEntries?.some((entry) => entry.day === dayKey && (entry.sessionType === "game" || entry.sessionType === "game-training"));
    if (!isRecoveryCard && !isSingleOnlyCard && !isGameDay && isTodayOrFutureDate(dateKey) && !hasCompleted) {
      const disabledMap = { ...readManualDayDisabledMap(), [dateKey]: true };
      writeManualDayDisabledMap(disabledMap);
      setDisabledManualDays(disabledMap);
      syncNoTimeForDate(dateKey);
    }
    setSelectedWorkoutByDay((current) => ({ ...current, [dayByIndex[dayIndex]]: undefined }));
    setManualVersion((current) => current + 1);
  };

  const addManualGameForDay = (dayIndex: (typeof weekdayOrder)[number], kind: "game" | "game_training") => {
    const dateKey = addManualGameToWeekday(dayIndex, kind);
    if (!dateKey) return;
    const nextGameId = gamePlanId(dateKey, kind === "game_training" ? "game_training" : "game");

    // Falls der Tag zuvor auf "Keine Zeit" gesetzt war, beim manuellen Spiel wieder aktivieren.
    const disabledMap = readManualDayDisabledMap();
    if (disabledMap[dateKey]) {
      const nextDisabled = { ...disabledMap };
      delete nextDisabled[dateKey];
      writeManualDayDisabledMap(nextDisabled);
      setDisabledManualDays(nextDisabled);
    }

    // Versteckte Auto-Karten fuer den Tag zuruecksetzen, damit der neue Zustand klar sichtbar ist.
    const hiddenMap = readHiddenAutoWorkoutsMap();
    if (hiddenMap[dateKey]) {
      const nextHidden = { ...hiddenMap };
      delete nextHidden[dateKey];
      writeHiddenAutoWorkoutsMap(nextHidden);
      setHiddenAutoWorkoutsByDate(nextHidden);
    }

    setDailyPlanByDate(readDailyPlanMap());
    setSelectedWorkoutByDay((current) => ({ ...current, [dayByIndex[dayIndex]]: nextGameId }));
    setManualVersion((v) => v + 1);
  };

  return (
    <main className="app-container animate-in">
      <PageHeader
        eyebrow={mesocycleLabel ? `Mesozyklus · ${mesocycleLabel}` : "Wochenplan"}
        title="Weekly Workout"
        subtitle="Alle Tage sind direkt bearbeitbar – inklusive heute."
      />

      {todayIndex === null ? (
        <p className="mt-4 text-sm text-muted">Wochenplan wird geladen …</p>
      ) : (
        <>
      <div className="weekly-subnav-row">
        <TopSubTabs items={[{ label: "Weekly", href: "/weekly-workout" }, { label: "Training", href: "/training" }]} />
        <div className="weekly-subnav-row__actions">
          <Link
            href={`/workouts?day=${todayIndex}&manual=1`}
            className="icon-btn icon-btn--primary"
            aria-label="Workout hinzufügen"
            title="Workout hinzufügen"
          >
            <PlusIcon />
          </Link>
          <Link href="/tips" className="btn btn-ghost btn-sm">
            Tipps
          </Link>
        </div>
      </div>

      <PausedWorkoutsBanner className="mt-4" />

      <WeeklyPlanAiButton className="mt-4" onSynced={() => setProfileVersion((v) => v + 1)} />

      <p className="mt-3 text-xs text-faint">Tipp: Wenn noch alles leer ist, im Profil zuerst Trainings-Tage und Schwerpunkte setzen.</p>

      <WeeklyBasketballCoach refreshKey={manualVersion + profileVersion} />

      <div className="mt-6 space-y-3">
        {orderedDays.map((day) => {
          const workout = WEEKLY_WORKOUT_PLAN[day];
          const profilePlan = plannedEntries?.find((entry) => entry.day === dayByIndex[day]) ?? null;
          const suggestedWorkout = suggestionsByDay?.[dayByIndex[day]] ?? null;
          const autoSuggestedWorkout = autoSuggestionsByDay?.[dayByIndex[day]] ?? null;
          const manualDateKey = toLocalDateKey(getDateForWeekday(day));
          const dayManualEntries = manualWorkoutsByDate[manualDateKey] ?? [];
          const gameCard = getGameCardFromTags(
            manualDateKey,
            dailyPlanByDate[manualDateKey] ?? [],
            profilePlan?.minutes ?? 0,
            profilePlan?.sessionType,
          );
          const hiddenCardIds = new Set(hiddenAutoWorkoutsByDate[manualDateKey] ?? []);
          const autoWorkoutsHidden = hiddenCardIds.has(HIDE_ALL_AUTO_WORKOUTS_ID);
          const isDayDisabled = disabledManualDays[manualDateKey] === true;
          const hasManualWorkout = dayManualEntries.length > 0;
          const calendarBlocksTraining = calendarBlocksTrainingForDate(manualDateKey, {
            sessionType: profilePlan?.sessionType,
            minutes: profilePlan?.minutes,
          });
          const visibleSuggestedWorkout = autoWorkoutsHidden && hasManualWorkout ? null : suggestedWorkout;
          const isRestDisplay =
            !hasManualWorkout &&
            !gameCard &&
            (isDayDisabled ||
              calendarBlocksTraining ||
              (visibleSuggestedWorkout?.durationMin ?? 0) <= 0 ||
              visibleSuggestedWorkout?.sport === "-");
          let workoutCards: WorkoutCardItem[] = [];
          const shouldAddRecoveryCard =
            !isRestDisplay &&
            !calendarBlocksTraining &&
            autoSuggestedWorkout?.sport !== "Regeneration" &&
            !storedRegenerationSignals(manualDateKey) &&
            dayManualEntries[0]?.sport !== "Rest";
          if (dayManualEntries.length > 0) {
            dayManualEntries.forEach((manualEntry) => {
              workoutCards.push({
                id: manualEntry.id,
                title: manualEntry.title,
                sport: manualEntry.sport,
                subcategory: manualEntry.subcategory,
                notes: manualEntry.notes || "Manuell geplant.",
                manualWorkoutId: manualEntry.id,
                durationMin:
                  manualEntry.durationMin ??
                  (manualEntry.exerciseIds?.length
                    ? sumExerciseIdsDurationMin(manualEntry.exerciseIds, exercisesById)
                    : suggestedWorkout?.durationMin ?? 0),
              });
            });
          }
          if (autoSuggestedWorkout && !isDayDisabled && !autoWorkoutsHidden && !calendarBlocksTraining) {
            const autoWorkoutId = autoSuggestedWorkout.workoutId ?? buildAutoWorkoutId(day, autoSuggestedWorkout.sport);
            if (!hiddenCardIds.has(autoWorkoutId)) {
              workoutCards.push({
                id: autoWorkoutId,
                title: autoSuggestedWorkout.title,
                sport: autoSuggestedWorkout.sport,
                subcategory: autoSuggestedWorkout.subcategory,
                notes: autoSuggestedWorkout.notes,
                workoutId: autoWorkoutId,
                autoSuggestion: autoSuggestedWorkout.workoutId ? undefined : autoSuggestedWorkout,
                durationMin: autoSuggestedWorkout.durationMin,
              });
            }
          }
          if (shouldAddRecoveryCard) {
            const recoverySuggestion = buildRecoverySuggestion(dayByIndex[day], availableExercises);
            const recoveryCardId = `recovery-${manualDateKey}`;
            const recoveryWorkoutId = buildAutoWorkoutId(day, recoverySuggestion.sport);
            if (!hiddenCardIds.has(recoveryCardId)) {
              workoutCards.push({
                id: recoveryCardId,
                title: recoverySuggestion.title,
                sport: recoverySuggestion.sport,
                subcategory: recoverySuggestion.subcategory,
                notes: recoverySuggestion.notes,
                workoutId: recoveryWorkoutId,
                autoSuggestion: recoverySuggestion,
                durationMin: recoverySuggestion.durationMin,
              });
            }
          }
          if (gameCard) {
            const existingWarmupCards = workoutCards.filter(isWarmupCard);
            workoutCards = workoutCards.filter((card) => !isWarmupCard(card));
            const visibleWarmups = warmupCatalogWorkouts.filter((workout) => !hiddenCardIds.has(workout.id));
            const selectedWarmupId = selectedWarmupByDate[manualDateKey] ?? visibleWarmups[0]?.id;
            const workout = visibleWarmups.find((item) => item.id === selectedWarmupId) ?? visibleWarmups[0];
            if (workout) {
              workoutCards.push({
                id: workout.id,
                title: workout.name,
                sport: workout.category,
                subcategory: workout.subcategory,
                notes: workout.notes ?? "Warm-Up vor Spieltag/Spieltraining.",
                workoutId: workout.id,
                durationMin: computeWorkoutDuration(workout, exercisesById),
              });
            } else if (existingWarmupCards[0]) {
              workoutCards.push(existingWarmupCards[0]);
            }
          }
          if (gameCard) {
            workoutCards.push(gameCard);
          }
          const hasWarmupBeforeGame = gameCard
            ? workoutCards.some((card) => card.id !== gameCard.id && isWarmupCard(card))
            : false;
          const orderedWorkoutCards = [...workoutCards].sort((left, right) => {
            const leftRecovery = isRegenerationCard(left);
            const rightRecovery = isRegenerationCard(right);
            if (leftRecovery === rightRecovery) return 0;
            return leftRecovery ? 1 : -1;
          });
          const totalWorkoutMinutes = orderedWorkoutCards.reduce((sum, card) => sum + Math.max(0, card.durationMin || 0), 0);
          const selectedCardId = selectedWorkoutByDay[dayByIndex[day]] ?? orderedWorkoutCards[0]?.id;
          const selectedCard = orderedWorkoutCards.find((entry) => entry.id === selectedCardId) ?? orderedWorkoutCards[0] ?? null;
          const completedIdsForDate = completedWorkoutIdsByDate[manualDateKey] ?? new Set<string>();
          const completedProgressIdsForDate = completedProgressIdsByDate[manualDateKey] ?? new Set<string>();
          const continuableProgressIdsForDate = continuableProgressIdsByDate[manualDateKey] ?? new Set<string>();
          const gameCompletedIdsForDate = new Set(
            loadGameStats()
              .filter((entry) => entry.date === manualDateKey)
              .map((entry) => gamePlanId(manualDateKey, entry.context === "game_training" ? "game_training" : "game")),
          );
          const cardIsCompleted = (card: WorkoutCardItem) =>
            card.kind === "game"
              ? gameCompletedIdsForDate.has(card.id)
              : getCompletionIdsForCard(card).some((id) => completedIdsForDate.has(id) || completedProgressIdsForDate.has(id));
          const completedCardsCount = orderedWorkoutCards.filter((card) => {
            return cardIsCompleted(card);
          }).length;
          const isSelectedCardCompleted = Boolean(
            selectedCard && cardIsCompleted(selectedCard),
          );
          const selectedCardCanContinue = Boolean(
            selectedCard &&
              !isSelectedCardCompleted &&
              getCompletionIdsForCard(selectedCard).some((id) => continuableProgressIdsForDate.has(id)),
          );
          const allCardsCompleted = orderedWorkoutCards.length > 0 && completedCardsCount === orderedWorkoutCards.length;
          const dateLabel = getDateForWeekday(day).toLocaleDateString("de-DE", { day: "2-digit", month: "2-digit" });

          return (
            <article
              key={day}
              className={`${day === todayIndex ? "app-card app-card--today" : "app-card"} ${
                allCardsCompleted ? "weekly-day-card--all-done" : ""
              }`}
            >
              <header className="flex items-center justify-between gap-3">
                <div>
                  <p className="section-eyebrow">{day === todayIndex ? "Heute" : dateLabel}</p>
                  <h3 className="mt-1 text-lg font-bold tracking-tight">{weekdayNames[day]}</h3>
                </div>
                <div className="flex flex-wrap items-center justify-end gap-1.5">
                  {allCardsCompleted ? (
                    <span className="chip chip-success weekly-day-done-chip shrink-0">Erledigt ✅</span>
                  ) : null}
                  {profilePlan ? (
                    <span className="chip">{totalWorkoutMinutes || profilePlan.minutes} Min</span>
                  ) : null}
                </div>
              </header>

              <p className="mt-3 text-base font-semibold text-strong">
                {isRestDisplay ? "Frei · Kein Workout geplant" : selectedCard?.title ?? visibleSuggestedWorkout?.title ?? workout.title}
              </p>
              {profilePlan ? (
                <p className="mt-1 text-xs text-muted">
                  Profil-Plan: <span className="text-strong">{profilePlan.sessionType}</span> · {profilePlan.intensity}
                </p>
              ) : null}
              {allCardsCompleted ? (
                <p className="weekly-day-done-banner mt-2 text-xs weekly-done-text">
                  Alle Einheiten erledigt.
                </p>
              ) : null}
              {gameCard && !hasWarmupBeforeGame ? (
                <p className="mt-2 alert-warning text-xs">
                  Kein Warm-Up-Workout gefunden. Erstelle am besten ein Basketball-Workout in der Unterkategorie <strong>Warm-Up</strong>, damit es vor {gameCard.title} angezeigt wird.
                </p>
              ) : null}
              {gameCard && warmupCatalogWorkouts.filter((warmup) => !hiddenCardIds.has(warmup.id)).length > 1 ? (
                <div className="weekly-panel">
                  <label className="input-label">Warm-Up auswählen</label>
                  <select
                    value={
                      selectedWarmupByDate[manualDateKey] ??
                      warmupCatalogWorkouts.find((warmup) => !hiddenCardIds.has(warmup.id))?.id ??
                      ""
                    }
                    onChange={(event) => {
                      const warmupId = event.target.value;
                      setSelectedWarmupByDate((current) => {
                        const next = { ...current, [manualDateKey]: warmupId };
                        writeSelectedWarmupByDate(next);
                        return next;
                      });
                      setSelectedWorkoutByDay((current) => ({ ...current, [dayByIndex[day]]: warmupId }));
                    }}
                    className="select mt-2"
                  >
                    {warmupCatalogWorkouts.filter((warmup) => !hiddenCardIds.has(warmup.id)).map((warmup) => (
                      <option key={warmup.id} value={warmup.id}>
                        {warmup.name}
                      </option>
                    ))}
                  </select>
                </div>
              ) : null}

              <div className="mt-4">
                {orderedWorkoutCards.length > 0 && !isRestDisplay ? (
                  <ShowMoreList
                    items={orderedWorkoutCards}
                    listClassName="grid gap-2 md:grid-cols-2"
                    getKey={(card, cardIndex) => `${day}-${card.id}-${cardIndex}`}
                    renderItem={(card) => {
                      const isDone = cardIsCompleted(card);
                      const isSelected = selectedCardId === card.id;
                      return (
                        <button
                          type="button"
                          onClick={() =>
                            setSelectedWorkoutByDay((current) => ({
                              ...current,
                              [dayByIndex[day]]: card.id,
                            }))
                          }
                          className={`weekly-workout-card ${
                            isDone
                              ? "weekly-workout-card--done weekly-workout-card-done"
                              : isSelected
                                ? "weekly-workout-card--selected"
                                : ""
                          }`}
                        >
                          <p className="flex items-center gap-2 font-semibold text-strong">
                            <span className="truncate">{card.title}</span>
                            {isDone ? <span className="weekly-done-text">✅</span> : null}
                          </p>
                          <p className="mt-1 text-xs text-muted">
                            {card.sport} · {card.subcategory}
                          </p>
                          <p className="mt-0.5 text-xs text-faint">{card.durationMin} Min</p>
                        </button>
                      );
                    }}
                  />
                ) : (
                  <p className="weekly-empty-hint">
                    {isRestDisplay
                      ? "Tag ist als Frei markiert. Versuche heute trotzdem eine kleine Aktivität 🙌"
                      : "Kein Workout hinterlegt."}
                  </p>
                )}
              </div>

              {selectedCard && !isRestDisplay ? (
                <div className="weekly-action-bar">
                  <div className="weekly-action-bar__main">
                    {isGameCard(selectedCard) ? (
                      <Link
                        href={`/game-track?date=${manualDateKey}&context=${gameContextForCard(selectedCard)}`}
                        className="btn btn-violet btn-xs"
                      >
                        Spiel tracken
                      </Link>
                    ) : (
                      <>
                        <button
                          type="button"
                          className="btn btn-primary btn-xs"
                          onClick={() =>
                            navigateToWeeklyWorkout(router, {
                              day,
                              mode: "start",
                              card: toNavCard(selectedCard),
                            })
                          }
                        >
                          {isSelectedCardCompleted
                            ? "Workout ansehen"
                            : selectedCardCanContinue
                              ? "Workout fortfahren"
                              : "Workout starten"}
                        </button>
                        <button
                          type="button"
                          className="btn btn-outline btn-xs"
                          onClick={() =>
                            navigateToWeeklyWorkout(router, {
                              day,
                              mode: "edit",
                              card: toNavCard(selectedCard),
                            })
                          }
                        >
                          Bearbeiten
                        </button>
                      </>
                    )}
                    <Link href={`/workouts?day=${day}&manual=1`} className="btn btn-emerald btn-xs">
                      + Workout
                    </Link>
                    <button
                      type="button"
                      onClick={() => {
                        if (selectedCard.manualWorkoutId) {
                          deleteManualWorkout(day, selectedCard.manualWorkoutId);
                          return;
                        }
                        hideAutoWorkoutCard(day, selectedCard.id);
                      }}
                      className="btn btn-danger-outline btn-xs"
                    >
                      {selectedCard.manualWorkoutId ? "Löschen" : "Ausblenden"}
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        if (selectedCard.manualWorkoutId) {
                          moveManualWorkoutToTomorrow(day, selectedCard.manualWorkoutId);
                          return;
                        }
                        moveAutoWorkoutToTomorrow(day, selectedCard);
                      }}
                      className="btn btn-cyan btn-xs"
                    >
                      Auf morgen
                    </button>
                    <button
                      type="button"
                      onClick={() => disableDayAsNoTime(day)}
                      className="btn btn-ghost btn-xs"
                    >
                      Keine Zeit
                    </button>
                  </div>
                  <div className="weekly-action-bar__game">
                    <button
                      type="button"
                      className="btn btn-outline btn-xs btn-weekly-game"
                      onClick={() => addManualGameForDay(day, "game")}
                    >
                      + Spieltag
                    </button>
                    <button
                      type="button"
                      className="btn btn-outline btn-xs btn-weekly-game"
                      onClick={() => addManualGameForDay(day, "game_training")}
                    >
                      + Spieltraining
                    </button>
                  </div>
                </div>
              ) : null}

              {selectedCard && !isRestDisplay && isGameCard(selectedCard) ? (
                <WeeklyGamePrepPanel
                  dateKey={manualDateKey}
                  context={gameContextForCard(selectedCard)}
                  onSaved={() => {
                    setProfileVersion((current) => current + 1);
                    window.dispatchEvent(new Event("bt:game-stats-updated"));
                  }}
                />
              ) : null}

              {!selectedCard || isRestDisplay ? (
                <div className="weekly-action-bar weekly-action-bar--empty">
                  <div className="weekly-action-bar__main">
                    <Link href={`/workouts?day=${day}&manual=1`} className="btn btn-emerald btn-xs">
                      Workout hinzufügen
                    </Link>
                    {!isRestDisplay ? null : (
                      <button
                        type="button"
                        onClick={() => disableDayAsNoTime(day)}
                        className="btn btn-ghost btn-xs"
                      >
                        Frei bestätigen
                      </button>
                    )}
                  </div>
                  <div className="weekly-action-bar__game">
                    <button
                      type="button"
                      className="btn btn-outline btn-xs btn-weekly-game"
                      onClick={() => addManualGameForDay(day, "game")}
                    >
                      + Spieltag
                    </button>
                    <button
                      type="button"
                      className="btn btn-outline btn-xs btn-weekly-game"
                      onClick={() => addManualGameForDay(day, "game_training")}
                    >
                      + Spieltraining
                    </button>
                  </div>
                </div>
              ) : null}

              {selectedCard && !isRestDisplay ? (
                <p className="mt-3 text-xs text-faint">{selectedCard.notes}</p>
              ) : isRestDisplay ? (
                <p className="mt-3 text-xs text-muted italic">
                  {REST_QUOTES[(day + new Date().getDate()) % REST_QUOTES.length]}
                </p>
              ) : (
                <GradientFadeList
                  className="mt-3"
                  items={workout.exercises}
                  listClassName="space-y-1 text-sm text-muted"
                  getKey={(exercise) => `${workout.id}-${exercise.name}`}
                  renderItem={(exercise) => (
                    <div className="flex gap-2">
                      <span aria-hidden className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--brand-500)]" />
                      <span>{exercise.name}</span>
                    </div>
                  )}
                />
              )}
            </article>
          );
        })}
      </div>
        </>
      )}
    </main>
  );
}
